// Package base64 is a drop-in fast path for standard base64 (StdEncoding,
// padded). The bulk of encoding and decoding runs a SIMD kernel generated by
// go-asmgen (amd64 SSE/AVX2, ppc64le VSX, s390x vector facility, arm64 NEON for
// both encode and decode); other arches fall back to the standard library, and
// the short tail/padding always use encoding/base64 so output is byte-identical
// to base64.StdEncoding.
package base64

import "encoding/base64"

// EncodedLen returns the length in bytes of the base64 encoding of n input bytes.
func EncodedLen(n int) int { return base64.StdEncoding.EncodedLen(n) }

// Encode writes the StdEncoding base64 of src into dst (len(dst) >= EncodedLen).
func Encode(dst, src []byte) {
	sd, dd := encodeSIMD(dst, src)
	base64.StdEncoding.Encode(dst[dd:], src[sd:])
}

// EncodeToString returns the StdEncoding base64 of src.
func EncodeToString(src []byte) string {
	dst := make([]byte, EncodedLen(len(src)))
	Encode(dst, src)
	return string(dst)
}

// DecodedLen returns the max decoded length of n base64 bytes.
func DecodedLen(n int) int { return base64.StdEncoding.DecodedLen(n) }

// Decode decodes StdEncoding base64 src into dst. A SIMD kernel handles the bulk
// of clean (no-padding, no-whitespace, all-valid) full blocks; the remainder —
// the final padded quantum and any block containing an invalid byte — is handed
// to encoding/base64 so the result is byte- and error-identical (CorruptInputError
// offsets match exactly).
func Decode(dst, src []byte) (int, error) {
	sd, dd := decodeSIMD(dst, src)
	n, err := base64.StdEncoding.Decode(dst[dd:], src[sd:])
	// StdEncoding.Decode only ever reports a CorruptInputError; re-base its offset
	// onto the original src so it matches a single stdlib Decode of the whole input.
	if ce, ok := err.(base64.CorruptInputError); ok {
		return dd + n, base64.CorruptInputError(int(ce) + sd)
	}
	return dd + n, err
}

// DecodeString decodes a StdEncoding base64 string.
func DecodeString(s string) ([]byte, error) {
	dst := make([]byte, DecodedLen(len(s)))
	n, err := Decode(dst, []byte(s))
	return dst[:n], err
}
