// Package base64 is a drop-in fast path for standard base64 (StdEncoding,
// padded). The bulk of encoding runs a SIMD kernel generated by go-asmgen
// (amd64 SSE today; other arches fall back to the standard library), the short
// tail and padding use encoding/base64 so output is byte-identical to
// base64.StdEncoding.
package base64

import "encoding/base64"

// EncodedLen returns the length in bytes of the base64 encoding of n input bytes.
func EncodedLen(n int) int { return base64.StdEncoding.EncodedLen(n) }

// Encode writes the StdEncoding base64 of src into dst (len(dst) >= EncodedLen).
func Encode(dst, src []byte) {
	sd, dd := encodeSIMD(dst, src)
	base64.StdEncoding.Encode(dst[dd:], src[sd:])
}

// EncodeToString returns the StdEncoding base64 of src.
func EncodeToString(src []byte) string {
	dst := make([]byte, EncodedLen(len(src)))
	Encode(dst, src)
	return string(dst)
}

// DecodedLen returns the max decoded length of n base64 bytes.
func DecodedLen(n int) int { return base64.StdEncoding.DecodedLen(n) }

// Decode decodes StdEncoding base64 src into dst. (Scalar for now; a SIMD decode
// kernel is planned.)
func Decode(dst, src []byte) (int, error) { return base64.StdEncoding.Decode(dst, src) }

// DecodeString decodes a StdEncoding base64 string.
func DecodeString(s string) ([]byte, error) { return base64.StdEncoding.DecodeString(s) }
