// Package base64 is a drop-in fast path for standard base64, byte- AND
// error-identical to encoding/base64. It mirrors the four stdlib encodings —
// StdEncoding (A-Za-z0-9+/, padded), URLEncoding (A-Za-z0-9-_, padded),
// RawStdEncoding (+/, no padding) and RawURLEncoding (-_, no padding) — and the
// bulk of encoding and decoding runs a SIMD kernel generated by go-asmgen (amd64
// SSE/AVX2, ppc64le VSX, s390x vector facility, arm64 NEON for both encode and
// decode); other arches fall back to the standard library, and the short
// tail/padding always use encoding/base64 so output is byte-identical to the
// matching base64.Encoding.
//
// The SIMD kernels come in two alphabets (+/ for Std/RawStd, -_ for URL/RawURL);
// padding is a tail concern handled entirely by the wrapped encoding/base64
// encoding, so the padded and raw variants share the same kernel.
package base64

import "encoding/base64"

// An Encoding is a base64 codec (one of the four package-level encodings). It
// wraps the matching encoding/base64.Encoding for the tail/padding so every
// result — including each CorruptInputError offset — is identical to the stdlib.
type Encoding struct {
	std *base64.Encoding // the matching stdlib encoding (handles tail + padding)
	url bool             // true => -_ alphabet (URL/RawURL), false => +/ (Std/RawStd)
}

// The four encodings mirror encoding/base64's StdEncoding, URLEncoding,
// RawStdEncoding and RawURLEncoding exactly.
var (
	StdEncoding    = &Encoding{std: base64.StdEncoding, url: false}
	URLEncoding    = &Encoding{std: base64.URLEncoding, url: true}
	RawStdEncoding = &Encoding{std: base64.RawStdEncoding, url: false}
	RawURLEncoding = &Encoding{std: base64.RawURLEncoding, url: true}
)

// EncodedLen returns the length in bytes of the base64 encoding of n input bytes.
func (enc *Encoding) EncodedLen(n int) int { return enc.std.EncodedLen(n) }

// Encode writes the base64 of src into dst (len(dst) >= EncodedLen(len(src))).
func (enc *Encoding) Encode(dst, src []byte) {
	// Below encodeSIMDMin input bytes no arch's kernel runs (amd64 SSE 16,
	// arm64 NEON 48), so encode tiny inputs straight via the stdlib and match it
	// exactly rather than pay an extra frame for no SIMD work.
	if len(src) < encodeSIMDMin {
		enc.std.Encode(dst, src)
		return
	}
	sd, dd := encodeSIMD(dst, src, enc.url)
	enc.std.Encode(dst[dd:], src[sd:])
}

// EncodeToString returns the base64 of src.
func (enc *Encoding) EncodeToString(src []byte) string {
	dst := make([]byte, enc.EncodedLen(len(src)))
	enc.Encode(dst, src)
	return string(dst)
}

// DecodedLen returns the max decoded length of n base64 bytes.
func (enc *Encoding) DecodedLen(n int) int { return enc.std.DecodedLen(n) }

// Decode decodes base64 src into dst. A SIMD kernel handles the bulk of clean
// (no-padding, no-whitespace, all-valid) full blocks; the remainder — the final
// padded quantum and any block containing an invalid byte — is handed to
// encoding/base64 so the result is byte- and error-identical (CorruptInputError
// offsets match exactly).
func (enc *Encoding) Decode(dst, src []byte) (int, error) {
	// Below decodeSIMDMin src chars no arch's kernel runs (amd64 SSE/ppc64le/s390x
	// 16+8, arm64 NEON 64), so hand short inputs straight to the stdlib and skip
	// the decodeSIMD call + offset-rebase. This keeps small inputs exactly as fast
	// as encoding/base64 — a SIMD path is never slower than stdlib. The threshold
	// is per-arch so 24..63-char inputs still take the SIMD path where it exists.
	if len(src) < decodeSIMDMin {
		return enc.std.Decode(dst, src)
	}
	sd, dd := decodeSIMD(dst, src, enc.url)
	n, err := enc.std.Decode(dst[dd:], src[sd:])
	// Decode only ever reports a CorruptInputError; re-base its offset onto the
	// original src so it matches a single stdlib Decode of the whole input.
	if ce, ok := err.(base64.CorruptInputError); ok {
		return dd + n, base64.CorruptInputError(int(ce) + sd)
	}
	return dd + n, err
}

// DecodeString decodes a base64 string.
func (enc *Encoding) DecodeString(s string) ([]byte, error) {
	dst := make([]byte, enc.DecodedLen(len(s)))
	n, err := enc.Decode(dst, []byte(s))
	return dst[:n], err
}

// Package-level helpers for StdEncoding (backwards-compatible with the original
// API, which exposed only StdEncoding).

// EncodedLen returns the length in bytes of the StdEncoding base64 of n bytes.
func EncodedLen(n int) int { return StdEncoding.EncodedLen(n) }

// Encode writes the StdEncoding base64 of src into dst.
func Encode(dst, src []byte) { StdEncoding.Encode(dst, src) }

// EncodeToString returns the StdEncoding base64 of src.
func EncodeToString(src []byte) string { return StdEncoding.EncodeToString(src) }

// DecodedLen returns the max decoded length of n StdEncoding base64 bytes.
func DecodedLen(n int) int { return StdEncoding.DecodedLen(n) }

// Decode decodes StdEncoding base64 src into dst.
func Decode(dst, src []byte) (int, error) { return StdEncoding.Decode(dst, src) }

// DecodeString decodes a StdEncoding base64 string.
func DecodeString(s string) ([]byte, error) { return StdEncoding.DecodeString(s) }
