//go:build amd64

package base64

import "golang.org/x/sys/cpu"

// decodeBlocksSSE decodes up to n groups of 16 base64 chars into 12 bytes each
// (Lemire/Muła vectorised decode). decodeBlocksAVX2 does 32 chars -> 24 bytes
// per group. Each returns the number of *groups* it fully decoded before either
// running out of groups or hitting a block that contains an invalid base64 byte
// (whitespace, padding '=', or any non-alphabet char); the caller decodes the
// remainder with encoding/base64 so errors and the padded tail are exact.
// Generated by go-asmgen (decode_gen.go), in decode_amd64.s. The URL-suffixed pair
// is the same kernel with the -_ alphabet's translate/validate LUTs.
func decodeBlocksSSE(dst, src []byte, n int) int
func decodeBlocksAVX2(dst, src []byte, n int) int
func decodeBlocksSSEURL(dst, src []byte, n int) int
func decodeBlocksAVX2URL(dst, src []byte, n int) int

var hasAVX2Decode = cpu.X86.HasAVX2

// decodeSIMD decodes the clean leading blocks of src (no padding, no whitespace,
// all-valid) with the widest available kernel, reporting bytes consumed in src
// and written in dst so the caller finishes the tail (the final padded quantum,
// or the first block containing an invalid byte) with encoding/base64.
//
// Both kernels write a full vector (16 bytes SSE, 32 bytes AVX2) per group but
// advance dst by only the 12/24 meaningful bytes, so every store over-writes the
// next group's slot (rewritten the next iteration). To keep the final group's
// over-store in bounds we reserve a trailing source span big enough that the
// scalar tail decoded into dst covers the overrun (and where StdEncoding padding
// lives): 12 src bytes for AVX2 (8-byte overrun) and 8 for SSE (4-byte overrun).
func decodeSIMD(dst, src []byte, url bool) (srcDone, dstDone int) {
	n := len(src)
	if hasAVX2Decode && n >= 32+12 {
		usable := n - 12
		groups := usable / 32
		var got int
		if url {
			got = decodeBlocksAVX2URL(dst, src, groups)
		} else {
			got = decodeBlocksAVX2(dst, src, groups)
		}
		return got * 32, got * 24
	}
	if n >= 16+8 {
		usable := n - 8
		groups := usable / 16
		var got int
		if url {
			got = decodeBlocksSSEURL(dst, src, groups)
		} else {
			got = decodeBlocksSSE(dst, src, groups)
		}
		return got * 16, got * 12
	}
	return 0, 0
}
