// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·decodeBlocks(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R3
	MOVD src_base+24(FP), R4
	MOVD n+48(FP), R5
	MOVD $dppcLutLo<>(SB), R6
	LXVB16X (R6)(R0), VS39
	MOVD $dppcLutHi<>(SB), R6
	LXVB16X (R6)(R0), VS40
	MOVD $dppcLutRoll<>(SB), R6
	LXVB16X (R6)(R0), VS41
	MOVD $dppcS6<>(SB), R6
	LXVB16X (R6)(R0), VS42
	MOVD $dppcS4<>(SB), R6
	LXVB16X (R6)(R0), VS43
	MOVD $dppcS2<>(SB), R6
	LXVB16X (R6)(R0), VS44
	MOVD $dppcM0<>(SB), R6
	LXVB16X (R6)(R0), VS45
	MOVD $dppcM1<>(SB), R6
	LXVB16X (R6)(R0), VS46
	MOVD $dppcM2<>(SB), R6
	LXVB16X (R6)(R0), VS47
	MOVD $dppcM3<>(SB), R6
	LXVB16X (R6)(R0), VS48
	MOVD $dppcPshuf<>(SB), R6
	LXVB16X (R6)(R0), VS49
	MOVD $dppcC2f<>(SB), R6
	LXVB16X (R6)(R0), VS50
	MOVD $dppcZero<>(SB), R6
	LXVB16X (R6)(R0), VS51
	MOVD $dppcC0f<>(SB), R6
	LXVB16X (R6)(R0), VS52
	VSPLTISB $4, V21
	MOVD $0, R7
	CMP R5, $0
	BEQ done
loop:
	LXVB16X (R4)(R0), VS32
	VAND V0, V20, V1
	VSRB V0, V21, V2
	VPERM V7, V7, V1, V3
	VPERM V8, V8, V2, V4
	VAND V3, V4, V5
	VCMPEQUBCC V5, V19, V6
	BC 4, 24, done
	VCMPEQUB V0, V18, V6
	VADDUBM V2, V6, V6
	VPERM V9, V9, V6, V6
	VADDUBM V0, V6, V0
	VSRW V0, V10, V1
	VAND V1, V13, V1
	VSRW V0, V11, V2
	VAND V2, V14, V2
	VOR V2, V1, V1
	VSRW V0, V12, V2
	VAND V2, V15, V2
	VOR V2, V1, V1
	VAND V0, V16, V2
	VOR V2, V1, V1
	VPERM V1, V1, V17, V1
	STXVB16X VS33, (R3)(R0)
	ADD $16, R4
	ADD $12, R3
	ADD $1, R7
	ADD $-1, R5
	CMP R5, $0
	BNE loop
done:
	MOVD R7, ret+56(FP)
	RET

DATA dppcLutLo<>+0(SB)/1, $0x15
DATA dppcLutLo<>+1(SB)/1, $0x11
DATA dppcLutLo<>+2(SB)/1, $0x11
DATA dppcLutLo<>+3(SB)/1, $0x11
DATA dppcLutLo<>+4(SB)/1, $0x11
DATA dppcLutLo<>+5(SB)/1, $0x11
DATA dppcLutLo<>+6(SB)/1, $0x11
DATA dppcLutLo<>+7(SB)/1, $0x11
DATA dppcLutLo<>+8(SB)/1, $0x11
DATA dppcLutLo<>+9(SB)/1, $0x11
DATA dppcLutLo<>+10(SB)/1, $0x13
DATA dppcLutLo<>+11(SB)/1, $0x1a
DATA dppcLutLo<>+12(SB)/1, $0x1b
DATA dppcLutLo<>+13(SB)/1, $0x1b
DATA dppcLutLo<>+14(SB)/1, $0x1b
DATA dppcLutLo<>+15(SB)/1, $0x1a
GLOBL dppcLutLo<>(SB), RODATA|NOPTR, $16

DATA dppcLutHi<>+0(SB)/1, $0x10
DATA dppcLutHi<>+1(SB)/1, $0x10
DATA dppcLutHi<>+2(SB)/1, $0x01
DATA dppcLutHi<>+3(SB)/1, $0x02
DATA dppcLutHi<>+4(SB)/1, $0x04
DATA dppcLutHi<>+5(SB)/1, $0x08
DATA dppcLutHi<>+6(SB)/1, $0x04
DATA dppcLutHi<>+7(SB)/1, $0x08
DATA dppcLutHi<>+8(SB)/1, $0x10
DATA dppcLutHi<>+9(SB)/1, $0x10
DATA dppcLutHi<>+10(SB)/1, $0x10
DATA dppcLutHi<>+11(SB)/1, $0x10
DATA dppcLutHi<>+12(SB)/1, $0x10
DATA dppcLutHi<>+13(SB)/1, $0x10
DATA dppcLutHi<>+14(SB)/1, $0x10
DATA dppcLutHi<>+15(SB)/1, $0x10
GLOBL dppcLutHi<>(SB), RODATA|NOPTR, $16

DATA dppcLutRoll<>+0(SB)/1, $0x00
DATA dppcLutRoll<>+1(SB)/1, $0x10
DATA dppcLutRoll<>+2(SB)/1, $0x13
DATA dppcLutRoll<>+3(SB)/1, $0x04
DATA dppcLutRoll<>+4(SB)/1, $0xbf
DATA dppcLutRoll<>+5(SB)/1, $0xbf
DATA dppcLutRoll<>+6(SB)/1, $0xb9
DATA dppcLutRoll<>+7(SB)/1, $0xb9
DATA dppcLutRoll<>+8(SB)/1, $0x00
DATA dppcLutRoll<>+9(SB)/1, $0x00
DATA dppcLutRoll<>+10(SB)/1, $0x00
DATA dppcLutRoll<>+11(SB)/1, $0x00
DATA dppcLutRoll<>+12(SB)/1, $0x00
DATA dppcLutRoll<>+13(SB)/1, $0x00
DATA dppcLutRoll<>+14(SB)/1, $0x00
DATA dppcLutRoll<>+15(SB)/1, $0x00
GLOBL dppcLutRoll<>(SB), RODATA|NOPTR, $16

DATA dppcS6<>+0(SB)/1, $0x00
DATA dppcS6<>+1(SB)/1, $0x00
DATA dppcS6<>+2(SB)/1, $0x00
DATA dppcS6<>+3(SB)/1, $0x06
DATA dppcS6<>+4(SB)/1, $0x00
DATA dppcS6<>+5(SB)/1, $0x00
DATA dppcS6<>+6(SB)/1, $0x00
DATA dppcS6<>+7(SB)/1, $0x06
DATA dppcS6<>+8(SB)/1, $0x00
DATA dppcS6<>+9(SB)/1, $0x00
DATA dppcS6<>+10(SB)/1, $0x00
DATA dppcS6<>+11(SB)/1, $0x06
DATA dppcS6<>+12(SB)/1, $0x00
DATA dppcS6<>+13(SB)/1, $0x00
DATA dppcS6<>+14(SB)/1, $0x00
DATA dppcS6<>+15(SB)/1, $0x06
GLOBL dppcS6<>(SB), RODATA|NOPTR, $16

DATA dppcS4<>+0(SB)/1, $0x00
DATA dppcS4<>+1(SB)/1, $0x00
DATA dppcS4<>+2(SB)/1, $0x00
DATA dppcS4<>+3(SB)/1, $0x04
DATA dppcS4<>+4(SB)/1, $0x00
DATA dppcS4<>+5(SB)/1, $0x00
DATA dppcS4<>+6(SB)/1, $0x00
DATA dppcS4<>+7(SB)/1, $0x04
DATA dppcS4<>+8(SB)/1, $0x00
DATA dppcS4<>+9(SB)/1, $0x00
DATA dppcS4<>+10(SB)/1, $0x00
DATA dppcS4<>+11(SB)/1, $0x04
DATA dppcS4<>+12(SB)/1, $0x00
DATA dppcS4<>+13(SB)/1, $0x00
DATA dppcS4<>+14(SB)/1, $0x00
DATA dppcS4<>+15(SB)/1, $0x04
GLOBL dppcS4<>(SB), RODATA|NOPTR, $16

DATA dppcS2<>+0(SB)/1, $0x00
DATA dppcS2<>+1(SB)/1, $0x00
DATA dppcS2<>+2(SB)/1, $0x00
DATA dppcS2<>+3(SB)/1, $0x02
DATA dppcS2<>+4(SB)/1, $0x00
DATA dppcS2<>+5(SB)/1, $0x00
DATA dppcS2<>+6(SB)/1, $0x00
DATA dppcS2<>+7(SB)/1, $0x02
DATA dppcS2<>+8(SB)/1, $0x00
DATA dppcS2<>+9(SB)/1, $0x00
DATA dppcS2<>+10(SB)/1, $0x00
DATA dppcS2<>+11(SB)/1, $0x02
DATA dppcS2<>+12(SB)/1, $0x00
DATA dppcS2<>+13(SB)/1, $0x00
DATA dppcS2<>+14(SB)/1, $0x00
DATA dppcS2<>+15(SB)/1, $0x02
GLOBL dppcS2<>(SB), RODATA|NOPTR, $16

DATA dppcM0<>+0(SB)/1, $0x00
DATA dppcM0<>+1(SB)/1, $0xfc
DATA dppcM0<>+2(SB)/1, $0x00
DATA dppcM0<>+3(SB)/1, $0x00
DATA dppcM0<>+4(SB)/1, $0x00
DATA dppcM0<>+5(SB)/1, $0xfc
DATA dppcM0<>+6(SB)/1, $0x00
DATA dppcM0<>+7(SB)/1, $0x00
DATA dppcM0<>+8(SB)/1, $0x00
DATA dppcM0<>+9(SB)/1, $0xfc
DATA dppcM0<>+10(SB)/1, $0x00
DATA dppcM0<>+11(SB)/1, $0x00
DATA dppcM0<>+12(SB)/1, $0x00
DATA dppcM0<>+13(SB)/1, $0xfc
DATA dppcM0<>+14(SB)/1, $0x00
DATA dppcM0<>+15(SB)/1, $0x00
GLOBL dppcM0<>(SB), RODATA|NOPTR, $16

DATA dppcM1<>+0(SB)/1, $0x00
DATA dppcM1<>+1(SB)/1, $0x03
DATA dppcM1<>+2(SB)/1, $0xf0
DATA dppcM1<>+3(SB)/1, $0x00
DATA dppcM1<>+4(SB)/1, $0x00
DATA dppcM1<>+5(SB)/1, $0x03
DATA dppcM1<>+6(SB)/1, $0xf0
DATA dppcM1<>+7(SB)/1, $0x00
DATA dppcM1<>+8(SB)/1, $0x00
DATA dppcM1<>+9(SB)/1, $0x03
DATA dppcM1<>+10(SB)/1, $0xf0
DATA dppcM1<>+11(SB)/1, $0x00
DATA dppcM1<>+12(SB)/1, $0x00
DATA dppcM1<>+13(SB)/1, $0x03
DATA dppcM1<>+14(SB)/1, $0xf0
DATA dppcM1<>+15(SB)/1, $0x00
GLOBL dppcM1<>(SB), RODATA|NOPTR, $16

DATA dppcM2<>+0(SB)/1, $0x00
DATA dppcM2<>+1(SB)/1, $0x00
DATA dppcM2<>+2(SB)/1, $0x0f
DATA dppcM2<>+3(SB)/1, $0xc0
DATA dppcM2<>+4(SB)/1, $0x00
DATA dppcM2<>+5(SB)/1, $0x00
DATA dppcM2<>+6(SB)/1, $0x0f
DATA dppcM2<>+7(SB)/1, $0xc0
DATA dppcM2<>+8(SB)/1, $0x00
DATA dppcM2<>+9(SB)/1, $0x00
DATA dppcM2<>+10(SB)/1, $0x0f
DATA dppcM2<>+11(SB)/1, $0xc0
DATA dppcM2<>+12(SB)/1, $0x00
DATA dppcM2<>+13(SB)/1, $0x00
DATA dppcM2<>+14(SB)/1, $0x0f
DATA dppcM2<>+15(SB)/1, $0xc0
GLOBL dppcM2<>(SB), RODATA|NOPTR, $16

DATA dppcM3<>+0(SB)/1, $0x00
DATA dppcM3<>+1(SB)/1, $0x00
DATA dppcM3<>+2(SB)/1, $0x00
DATA dppcM3<>+3(SB)/1, $0x3f
DATA dppcM3<>+4(SB)/1, $0x00
DATA dppcM3<>+5(SB)/1, $0x00
DATA dppcM3<>+6(SB)/1, $0x00
DATA dppcM3<>+7(SB)/1, $0x3f
DATA dppcM3<>+8(SB)/1, $0x00
DATA dppcM3<>+9(SB)/1, $0x00
DATA dppcM3<>+10(SB)/1, $0x00
DATA dppcM3<>+11(SB)/1, $0x3f
DATA dppcM3<>+12(SB)/1, $0x00
DATA dppcM3<>+13(SB)/1, $0x00
DATA dppcM3<>+14(SB)/1, $0x00
DATA dppcM3<>+15(SB)/1, $0x3f
GLOBL dppcM3<>(SB), RODATA|NOPTR, $16

DATA dppcPshuf<>+0(SB)/1, $0x01
DATA dppcPshuf<>+1(SB)/1, $0x02
DATA dppcPshuf<>+2(SB)/1, $0x03
DATA dppcPshuf<>+3(SB)/1, $0x05
DATA dppcPshuf<>+4(SB)/1, $0x06
DATA dppcPshuf<>+5(SB)/1, $0x07
DATA dppcPshuf<>+6(SB)/1, $0x09
DATA dppcPshuf<>+7(SB)/1, $0x0a
DATA dppcPshuf<>+8(SB)/1, $0x0b
DATA dppcPshuf<>+9(SB)/1, $0x0d
DATA dppcPshuf<>+10(SB)/1, $0x0e
DATA dppcPshuf<>+11(SB)/1, $0x0f
DATA dppcPshuf<>+12(SB)/1, $0x00
DATA dppcPshuf<>+13(SB)/1, $0x00
DATA dppcPshuf<>+14(SB)/1, $0x00
DATA dppcPshuf<>+15(SB)/1, $0x00
GLOBL dppcPshuf<>(SB), RODATA|NOPTR, $16

DATA dppcC2f<>+0(SB)/1, $0x2f
DATA dppcC2f<>+1(SB)/1, $0x2f
DATA dppcC2f<>+2(SB)/1, $0x2f
DATA dppcC2f<>+3(SB)/1, $0x2f
DATA dppcC2f<>+4(SB)/1, $0x2f
DATA dppcC2f<>+5(SB)/1, $0x2f
DATA dppcC2f<>+6(SB)/1, $0x2f
DATA dppcC2f<>+7(SB)/1, $0x2f
DATA dppcC2f<>+8(SB)/1, $0x2f
DATA dppcC2f<>+9(SB)/1, $0x2f
DATA dppcC2f<>+10(SB)/1, $0x2f
DATA dppcC2f<>+11(SB)/1, $0x2f
DATA dppcC2f<>+12(SB)/1, $0x2f
DATA dppcC2f<>+13(SB)/1, $0x2f
DATA dppcC2f<>+14(SB)/1, $0x2f
DATA dppcC2f<>+15(SB)/1, $0x2f
GLOBL dppcC2f<>(SB), RODATA|NOPTR, $16

DATA dppcZero<>+0(SB)/1, $0x00
DATA dppcZero<>+1(SB)/1, $0x00
DATA dppcZero<>+2(SB)/1, $0x00
DATA dppcZero<>+3(SB)/1, $0x00
DATA dppcZero<>+4(SB)/1, $0x00
DATA dppcZero<>+5(SB)/1, $0x00
DATA dppcZero<>+6(SB)/1, $0x00
DATA dppcZero<>+7(SB)/1, $0x00
DATA dppcZero<>+8(SB)/1, $0x00
DATA dppcZero<>+9(SB)/1, $0x00
DATA dppcZero<>+10(SB)/1, $0x00
DATA dppcZero<>+11(SB)/1, $0x00
DATA dppcZero<>+12(SB)/1, $0x00
DATA dppcZero<>+13(SB)/1, $0x00
DATA dppcZero<>+14(SB)/1, $0x00
DATA dppcZero<>+15(SB)/1, $0x00
GLOBL dppcZero<>(SB), RODATA|NOPTR, $16

DATA dppcC0f<>+0(SB)/1, $0x0f
DATA dppcC0f<>+1(SB)/1, $0x0f
DATA dppcC0f<>+2(SB)/1, $0x0f
DATA dppcC0f<>+3(SB)/1, $0x0f
DATA dppcC0f<>+4(SB)/1, $0x0f
DATA dppcC0f<>+5(SB)/1, $0x0f
DATA dppcC0f<>+6(SB)/1, $0x0f
DATA dppcC0f<>+7(SB)/1, $0x0f
DATA dppcC0f<>+8(SB)/1, $0x0f
DATA dppcC0f<>+9(SB)/1, $0x0f
DATA dppcC0f<>+10(SB)/1, $0x0f
DATA dppcC0f<>+11(SB)/1, $0x0f
DATA dppcC0f<>+12(SB)/1, $0x0f
DATA dppcC0f<>+13(SB)/1, $0x0f
DATA dppcC0f<>+14(SB)/1, $0x0f
DATA dppcC0f<>+15(SB)/1, $0x0f
GLOBL dppcC0f<>(SB), RODATA|NOPTR, $16

