// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·decodeBlocksSSE(SB), NOSPLIT, $0-64
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	MOVOU dlutLo<>+0(SB), X8
	MOVOU dlutHi<>+0(SB), X9
	MOVOU dlutRoll<>+0(SB), X10
	MOVOU dmul1<>+0(SB), X11
	MOVOU dmul2<>+0(SB), X12
	MOVOU dpshuf<>+0(SB), X13
	MOVOU dc0f<>+0(SB), X14
	MOVOU dc2f<>+0(SB), X15
	XORQ AX, AX
	TESTQ CX, CX
	JZ sdone
sloop:
	MOVOU (SI), X0
	MOVO X0, X1
	PSRLW $4, X1
	PAND X14, X1
	MOVO X0, X2
	PAND X14, X2
	MOVO X9, X3
	PSHUFB X1, X3
	MOVO X8, X4
	PSHUFB X2, X4
	PTEST X3, X4
	JNZ sdone
	MOVO X0, X6
	PCMPEQB X15, X6
	PADDB X1, X6
	MOVO X10, X7
	PSHUFB X6, X7
	PADDB X7, X0
	PMADDUBSW X11, X0
	PMADDWL X12, X0
	PSHUFB X13, X0
	MOVOU X0, (DI)
	ADDQ $16, SI
	ADDQ $12, DI
	INCQ AX
	DECQ CX
	JNZ sloop
sdone:
	MOVQ AX, ret+56(FP)
	RET

TEXT ·decodeBlocksAVX2(SB), NOSPLIT, $0-64
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VMOVDQU dlutLo<>+0(SB), Y8
	VMOVDQU dlutHi<>+0(SB), Y9
	VMOVDQU dlutRoll<>+0(SB), Y10
	VMOVDQU dmul1<>+0(SB), Y11
	VMOVDQU dmul2<>+0(SB), Y12
	VMOVDQU dpshuf<>+0(SB), Y13
	VMOVDQU dc0f<>+0(SB), Y14
	VMOVDQU dpermd<>+0(SB), Y15
	XORQ AX, AX
	TESTQ CX, CX
	JZ vdone
vloop:
	VMOVDQU (SI), Y0
	VPSRLW $4, Y0, Y1
	VPAND Y14, Y1, Y1
	VPAND Y14, Y0, Y2
	VPSHUFB Y1, Y9, Y3
	VPSHUFB Y2, Y8, Y4
	VPTEST Y3, Y4
	JNZ vdone
	VPCMPEQB dc2f<>+0(SB), Y0, Y6
	VPADDB Y1, Y6, Y6
	VPSHUFB Y6, Y10, Y7
	VPADDB Y7, Y0, Y0
	VPMADDUBSW Y11, Y0, Y0
	VPMADDWD Y12, Y0, Y0
	VPSHUFB Y13, Y0, Y0
	VPERMD Y0, Y15, Y0
	VMOVDQU Y0, (DI)
	ADDQ $32, SI
	ADDQ $24, DI
	INCQ AX
	DECQ CX
	JNZ vloop
vdone:
	MOVQ AX, ret+56(FP)
	VZEROUPPER
	RET

DATA dlutLo<>+0(SB)/1, $0x15
DATA dlutLo<>+1(SB)/1, $0x11
DATA dlutLo<>+2(SB)/1, $0x11
DATA dlutLo<>+3(SB)/1, $0x11
DATA dlutLo<>+4(SB)/1, $0x11
DATA dlutLo<>+5(SB)/1, $0x11
DATA dlutLo<>+6(SB)/1, $0x11
DATA dlutLo<>+7(SB)/1, $0x11
DATA dlutLo<>+8(SB)/1, $0x11
DATA dlutLo<>+9(SB)/1, $0x11
DATA dlutLo<>+10(SB)/1, $0x13
DATA dlutLo<>+11(SB)/1, $0x1a
DATA dlutLo<>+12(SB)/1, $0x1b
DATA dlutLo<>+13(SB)/1, $0x1b
DATA dlutLo<>+14(SB)/1, $0x1b
DATA dlutLo<>+15(SB)/1, $0x1a
DATA dlutLo<>+16(SB)/1, $0x15
DATA dlutLo<>+17(SB)/1, $0x11
DATA dlutLo<>+18(SB)/1, $0x11
DATA dlutLo<>+19(SB)/1, $0x11
DATA dlutLo<>+20(SB)/1, $0x11
DATA dlutLo<>+21(SB)/1, $0x11
DATA dlutLo<>+22(SB)/1, $0x11
DATA dlutLo<>+23(SB)/1, $0x11
DATA dlutLo<>+24(SB)/1, $0x11
DATA dlutLo<>+25(SB)/1, $0x11
DATA dlutLo<>+26(SB)/1, $0x13
DATA dlutLo<>+27(SB)/1, $0x1a
DATA dlutLo<>+28(SB)/1, $0x1b
DATA dlutLo<>+29(SB)/1, $0x1b
DATA dlutLo<>+30(SB)/1, $0x1b
DATA dlutLo<>+31(SB)/1, $0x1a
GLOBL dlutLo<>(SB), RODATA|NOPTR, $32

DATA dlutHi<>+0(SB)/1, $0x10
DATA dlutHi<>+1(SB)/1, $0x10
DATA dlutHi<>+2(SB)/1, $0x01
DATA dlutHi<>+3(SB)/1, $0x02
DATA dlutHi<>+4(SB)/1, $0x04
DATA dlutHi<>+5(SB)/1, $0x08
DATA dlutHi<>+6(SB)/1, $0x04
DATA dlutHi<>+7(SB)/1, $0x08
DATA dlutHi<>+8(SB)/1, $0x10
DATA dlutHi<>+9(SB)/1, $0x10
DATA dlutHi<>+10(SB)/1, $0x10
DATA dlutHi<>+11(SB)/1, $0x10
DATA dlutHi<>+12(SB)/1, $0x10
DATA dlutHi<>+13(SB)/1, $0x10
DATA dlutHi<>+14(SB)/1, $0x10
DATA dlutHi<>+15(SB)/1, $0x10
DATA dlutHi<>+16(SB)/1, $0x10
DATA dlutHi<>+17(SB)/1, $0x10
DATA dlutHi<>+18(SB)/1, $0x01
DATA dlutHi<>+19(SB)/1, $0x02
DATA dlutHi<>+20(SB)/1, $0x04
DATA dlutHi<>+21(SB)/1, $0x08
DATA dlutHi<>+22(SB)/1, $0x04
DATA dlutHi<>+23(SB)/1, $0x08
DATA dlutHi<>+24(SB)/1, $0x10
DATA dlutHi<>+25(SB)/1, $0x10
DATA dlutHi<>+26(SB)/1, $0x10
DATA dlutHi<>+27(SB)/1, $0x10
DATA dlutHi<>+28(SB)/1, $0x10
DATA dlutHi<>+29(SB)/1, $0x10
DATA dlutHi<>+30(SB)/1, $0x10
DATA dlutHi<>+31(SB)/1, $0x10
GLOBL dlutHi<>(SB), RODATA|NOPTR, $32

DATA dlutRoll<>+0(SB)/1, $0x00
DATA dlutRoll<>+1(SB)/1, $0x10
DATA dlutRoll<>+2(SB)/1, $0x13
DATA dlutRoll<>+3(SB)/1, $0x04
DATA dlutRoll<>+4(SB)/1, $0xbf
DATA dlutRoll<>+5(SB)/1, $0xbf
DATA dlutRoll<>+6(SB)/1, $0xb9
DATA dlutRoll<>+7(SB)/1, $0xb9
DATA dlutRoll<>+8(SB)/1, $0x00
DATA dlutRoll<>+9(SB)/1, $0x00
DATA dlutRoll<>+10(SB)/1, $0x00
DATA dlutRoll<>+11(SB)/1, $0x00
DATA dlutRoll<>+12(SB)/1, $0x00
DATA dlutRoll<>+13(SB)/1, $0x00
DATA dlutRoll<>+14(SB)/1, $0x00
DATA dlutRoll<>+15(SB)/1, $0x00
DATA dlutRoll<>+16(SB)/1, $0x00
DATA dlutRoll<>+17(SB)/1, $0x10
DATA dlutRoll<>+18(SB)/1, $0x13
DATA dlutRoll<>+19(SB)/1, $0x04
DATA dlutRoll<>+20(SB)/1, $0xbf
DATA dlutRoll<>+21(SB)/1, $0xbf
DATA dlutRoll<>+22(SB)/1, $0xb9
DATA dlutRoll<>+23(SB)/1, $0xb9
DATA dlutRoll<>+24(SB)/1, $0x00
DATA dlutRoll<>+25(SB)/1, $0x00
DATA dlutRoll<>+26(SB)/1, $0x00
DATA dlutRoll<>+27(SB)/1, $0x00
DATA dlutRoll<>+28(SB)/1, $0x00
DATA dlutRoll<>+29(SB)/1, $0x00
DATA dlutRoll<>+30(SB)/1, $0x00
DATA dlutRoll<>+31(SB)/1, $0x00
GLOBL dlutRoll<>(SB), RODATA|NOPTR, $32

DATA dmul1<>+0(SB)/1, $0x40
DATA dmul1<>+1(SB)/1, $0x01
DATA dmul1<>+2(SB)/1, $0x40
DATA dmul1<>+3(SB)/1, $0x01
DATA dmul1<>+4(SB)/1, $0x40
DATA dmul1<>+5(SB)/1, $0x01
DATA dmul1<>+6(SB)/1, $0x40
DATA dmul1<>+7(SB)/1, $0x01
DATA dmul1<>+8(SB)/1, $0x40
DATA dmul1<>+9(SB)/1, $0x01
DATA dmul1<>+10(SB)/1, $0x40
DATA dmul1<>+11(SB)/1, $0x01
DATA dmul1<>+12(SB)/1, $0x40
DATA dmul1<>+13(SB)/1, $0x01
DATA dmul1<>+14(SB)/1, $0x40
DATA dmul1<>+15(SB)/1, $0x01
DATA dmul1<>+16(SB)/1, $0x40
DATA dmul1<>+17(SB)/1, $0x01
DATA dmul1<>+18(SB)/1, $0x40
DATA dmul1<>+19(SB)/1, $0x01
DATA dmul1<>+20(SB)/1, $0x40
DATA dmul1<>+21(SB)/1, $0x01
DATA dmul1<>+22(SB)/1, $0x40
DATA dmul1<>+23(SB)/1, $0x01
DATA dmul1<>+24(SB)/1, $0x40
DATA dmul1<>+25(SB)/1, $0x01
DATA dmul1<>+26(SB)/1, $0x40
DATA dmul1<>+27(SB)/1, $0x01
DATA dmul1<>+28(SB)/1, $0x40
DATA dmul1<>+29(SB)/1, $0x01
DATA dmul1<>+30(SB)/1, $0x40
DATA dmul1<>+31(SB)/1, $0x01
GLOBL dmul1<>(SB), RODATA|NOPTR, $32

DATA dmul2<>+0(SB)/1, $0x00
DATA dmul2<>+1(SB)/1, $0x10
DATA dmul2<>+2(SB)/1, $0x01
DATA dmul2<>+3(SB)/1, $0x00
DATA dmul2<>+4(SB)/1, $0x00
DATA dmul2<>+5(SB)/1, $0x10
DATA dmul2<>+6(SB)/1, $0x01
DATA dmul2<>+7(SB)/1, $0x00
DATA dmul2<>+8(SB)/1, $0x00
DATA dmul2<>+9(SB)/1, $0x10
DATA dmul2<>+10(SB)/1, $0x01
DATA dmul2<>+11(SB)/1, $0x00
DATA dmul2<>+12(SB)/1, $0x00
DATA dmul2<>+13(SB)/1, $0x10
DATA dmul2<>+14(SB)/1, $0x01
DATA dmul2<>+15(SB)/1, $0x00
DATA dmul2<>+16(SB)/1, $0x00
DATA dmul2<>+17(SB)/1, $0x10
DATA dmul2<>+18(SB)/1, $0x01
DATA dmul2<>+19(SB)/1, $0x00
DATA dmul2<>+20(SB)/1, $0x00
DATA dmul2<>+21(SB)/1, $0x10
DATA dmul2<>+22(SB)/1, $0x01
DATA dmul2<>+23(SB)/1, $0x00
DATA dmul2<>+24(SB)/1, $0x00
DATA dmul2<>+25(SB)/1, $0x10
DATA dmul2<>+26(SB)/1, $0x01
DATA dmul2<>+27(SB)/1, $0x00
DATA dmul2<>+28(SB)/1, $0x00
DATA dmul2<>+29(SB)/1, $0x10
DATA dmul2<>+30(SB)/1, $0x01
DATA dmul2<>+31(SB)/1, $0x00
GLOBL dmul2<>(SB), RODATA|NOPTR, $32

DATA dpshuf<>+0(SB)/1, $0x02
DATA dpshuf<>+1(SB)/1, $0x01
DATA dpshuf<>+2(SB)/1, $0x00
DATA dpshuf<>+3(SB)/1, $0x06
DATA dpshuf<>+4(SB)/1, $0x05
DATA dpshuf<>+5(SB)/1, $0x04
DATA dpshuf<>+6(SB)/1, $0x0a
DATA dpshuf<>+7(SB)/1, $0x09
DATA dpshuf<>+8(SB)/1, $0x08
DATA dpshuf<>+9(SB)/1, $0x0e
DATA dpshuf<>+10(SB)/1, $0x0d
DATA dpshuf<>+11(SB)/1, $0x0c
DATA dpshuf<>+12(SB)/1, $0x80
DATA dpshuf<>+13(SB)/1, $0x80
DATA dpshuf<>+14(SB)/1, $0x80
DATA dpshuf<>+15(SB)/1, $0x80
DATA dpshuf<>+16(SB)/1, $0x02
DATA dpshuf<>+17(SB)/1, $0x01
DATA dpshuf<>+18(SB)/1, $0x00
DATA dpshuf<>+19(SB)/1, $0x06
DATA dpshuf<>+20(SB)/1, $0x05
DATA dpshuf<>+21(SB)/1, $0x04
DATA dpshuf<>+22(SB)/1, $0x0a
DATA dpshuf<>+23(SB)/1, $0x09
DATA dpshuf<>+24(SB)/1, $0x08
DATA dpshuf<>+25(SB)/1, $0x0e
DATA dpshuf<>+26(SB)/1, $0x0d
DATA dpshuf<>+27(SB)/1, $0x0c
DATA dpshuf<>+28(SB)/1, $0x80
DATA dpshuf<>+29(SB)/1, $0x80
DATA dpshuf<>+30(SB)/1, $0x80
DATA dpshuf<>+31(SB)/1, $0x80
GLOBL dpshuf<>(SB), RODATA|NOPTR, $32

DATA dc0f<>+0(SB)/1, $0x0f
DATA dc0f<>+1(SB)/1, $0x0f
DATA dc0f<>+2(SB)/1, $0x0f
DATA dc0f<>+3(SB)/1, $0x0f
DATA dc0f<>+4(SB)/1, $0x0f
DATA dc0f<>+5(SB)/1, $0x0f
DATA dc0f<>+6(SB)/1, $0x0f
DATA dc0f<>+7(SB)/1, $0x0f
DATA dc0f<>+8(SB)/1, $0x0f
DATA dc0f<>+9(SB)/1, $0x0f
DATA dc0f<>+10(SB)/1, $0x0f
DATA dc0f<>+11(SB)/1, $0x0f
DATA dc0f<>+12(SB)/1, $0x0f
DATA dc0f<>+13(SB)/1, $0x0f
DATA dc0f<>+14(SB)/1, $0x0f
DATA dc0f<>+15(SB)/1, $0x0f
DATA dc0f<>+16(SB)/1, $0x0f
DATA dc0f<>+17(SB)/1, $0x0f
DATA dc0f<>+18(SB)/1, $0x0f
DATA dc0f<>+19(SB)/1, $0x0f
DATA dc0f<>+20(SB)/1, $0x0f
DATA dc0f<>+21(SB)/1, $0x0f
DATA dc0f<>+22(SB)/1, $0x0f
DATA dc0f<>+23(SB)/1, $0x0f
DATA dc0f<>+24(SB)/1, $0x0f
DATA dc0f<>+25(SB)/1, $0x0f
DATA dc0f<>+26(SB)/1, $0x0f
DATA dc0f<>+27(SB)/1, $0x0f
DATA dc0f<>+28(SB)/1, $0x0f
DATA dc0f<>+29(SB)/1, $0x0f
DATA dc0f<>+30(SB)/1, $0x0f
DATA dc0f<>+31(SB)/1, $0x0f
GLOBL dc0f<>(SB), RODATA|NOPTR, $32

DATA dc2f<>+0(SB)/1, $0x2f
DATA dc2f<>+1(SB)/1, $0x2f
DATA dc2f<>+2(SB)/1, $0x2f
DATA dc2f<>+3(SB)/1, $0x2f
DATA dc2f<>+4(SB)/1, $0x2f
DATA dc2f<>+5(SB)/1, $0x2f
DATA dc2f<>+6(SB)/1, $0x2f
DATA dc2f<>+7(SB)/1, $0x2f
DATA dc2f<>+8(SB)/1, $0x2f
DATA dc2f<>+9(SB)/1, $0x2f
DATA dc2f<>+10(SB)/1, $0x2f
DATA dc2f<>+11(SB)/1, $0x2f
DATA dc2f<>+12(SB)/1, $0x2f
DATA dc2f<>+13(SB)/1, $0x2f
DATA dc2f<>+14(SB)/1, $0x2f
DATA dc2f<>+15(SB)/1, $0x2f
DATA dc2f<>+16(SB)/1, $0x2f
DATA dc2f<>+17(SB)/1, $0x2f
DATA dc2f<>+18(SB)/1, $0x2f
DATA dc2f<>+19(SB)/1, $0x2f
DATA dc2f<>+20(SB)/1, $0x2f
DATA dc2f<>+21(SB)/1, $0x2f
DATA dc2f<>+22(SB)/1, $0x2f
DATA dc2f<>+23(SB)/1, $0x2f
DATA dc2f<>+24(SB)/1, $0x2f
DATA dc2f<>+25(SB)/1, $0x2f
DATA dc2f<>+26(SB)/1, $0x2f
DATA dc2f<>+27(SB)/1, $0x2f
DATA dc2f<>+28(SB)/1, $0x2f
DATA dc2f<>+29(SB)/1, $0x2f
DATA dc2f<>+30(SB)/1, $0x2f
DATA dc2f<>+31(SB)/1, $0x2f
GLOBL dc2f<>(SB), RODATA|NOPTR, $32

DATA dpermd<>+0(SB)/1, $0x00
DATA dpermd<>+1(SB)/1, $0x00
DATA dpermd<>+2(SB)/1, $0x00
DATA dpermd<>+3(SB)/1, $0x00
DATA dpermd<>+4(SB)/1, $0x01
DATA dpermd<>+5(SB)/1, $0x00
DATA dpermd<>+6(SB)/1, $0x00
DATA dpermd<>+7(SB)/1, $0x00
DATA dpermd<>+8(SB)/1, $0x02
DATA dpermd<>+9(SB)/1, $0x00
DATA dpermd<>+10(SB)/1, $0x00
DATA dpermd<>+11(SB)/1, $0x00
DATA dpermd<>+12(SB)/1, $0x04
DATA dpermd<>+13(SB)/1, $0x00
DATA dpermd<>+14(SB)/1, $0x00
DATA dpermd<>+15(SB)/1, $0x00
DATA dpermd<>+16(SB)/1, $0x05
DATA dpermd<>+17(SB)/1, $0x00
DATA dpermd<>+18(SB)/1, $0x00
DATA dpermd<>+19(SB)/1, $0x00
DATA dpermd<>+20(SB)/1, $0x06
DATA dpermd<>+21(SB)/1, $0x00
DATA dpermd<>+22(SB)/1, $0x00
DATA dpermd<>+23(SB)/1, $0x00
DATA dpermd<>+24(SB)/1, $0x07
DATA dpermd<>+25(SB)/1, $0x00
DATA dpermd<>+26(SB)/1, $0x00
DATA dpermd<>+27(SB)/1, $0x00
DATA dpermd<>+28(SB)/1, $0x07
DATA dpermd<>+29(SB)/1, $0x00
DATA dpermd<>+30(SB)/1, $0x00
DATA dpermd<>+31(SB)/1, $0x00
GLOBL dpermd<>(SB), RODATA|NOPTR, $32

