// Code generated by go-asmgen. DO NOT EDIT.

//go:build s390x

#include "textflag.h"

TEXT ·decodeBlocks(SB), NOSPLIT, $0-64
	MOVD dst_base+0(FP), R1
	MOVD src_base+24(FP), R2
	MOVD n+48(FP), R3
	MOVD $ds390LutLo<>(SB), R4
	VL (R4), V16
	MOVD $ds390LutHi<>(SB), R4
	VL (R4), V17
	MOVD $ds390LutRoll<>(SB), R4
	VL (R4), V18
	MOVD $ds390M0<>(SB), R4
	VL (R4), V19
	MOVD $ds390M1<>(SB), R4
	VL (R4), V20
	MOVD $ds390M2<>(SB), R4
	VL (R4), V21
	MOVD $ds390M3<>(SB), R4
	VL (R4), V22
	MOVD $ds390C0f<>(SB), R4
	VL (R4), V23
	MOVD $ds390C2f<>(SB), R4
	VL (R4), V24
	MOVD $ds390Pshuf<>(SB), R4
	VL (R4), V25
	VZERO V26
	MOVD $0, R5
	CMPBEQ R3, $0, done
loop:
	VL (R2), V0
	VN V0, V23, V1
	VESRLB $4, V0, V2
	VPERM V16, V16, V1, V3
	VPERM V17, V17, V2, V4
	VN V3, V4, V5
	VCEQBS V5, V26, V6
	BNE done
	VCEQB V0, V24, V6
	VAB V2, V6, V6
	VPERM V18, V18, V6, V6
	VAB V0, V6, V0
	VESRLF $6, V0, V1
	VN V1, V19, V1
	VESRLF $4, V0, V2
	VN V2, V20, V2
	VO V2, V1, V1
	VESRLF $2, V0, V2
	VN V2, V21, V2
	VO V2, V1, V1
	VN V0, V22, V2
	VO V2, V1, V1
	VPERM V1, V1, V25, V1
	VST V1, (R1)
	ADD $16, R2
	ADD $12, R1
	ADD $1, R5
	ADD $-1, R3
	CMPBNE R3, $0, loop
done:
	MOVD R5, ret+56(FP)
	RET

DATA ds390LutLo<>+0(SB)/1, $0x15
DATA ds390LutLo<>+1(SB)/1, $0x11
DATA ds390LutLo<>+2(SB)/1, $0x11
DATA ds390LutLo<>+3(SB)/1, $0x11
DATA ds390LutLo<>+4(SB)/1, $0x11
DATA ds390LutLo<>+5(SB)/1, $0x11
DATA ds390LutLo<>+6(SB)/1, $0x11
DATA ds390LutLo<>+7(SB)/1, $0x11
DATA ds390LutLo<>+8(SB)/1, $0x11
DATA ds390LutLo<>+9(SB)/1, $0x11
DATA ds390LutLo<>+10(SB)/1, $0x13
DATA ds390LutLo<>+11(SB)/1, $0x1a
DATA ds390LutLo<>+12(SB)/1, $0x1b
DATA ds390LutLo<>+13(SB)/1, $0x1b
DATA ds390LutLo<>+14(SB)/1, $0x1b
DATA ds390LutLo<>+15(SB)/1, $0x1a
GLOBL ds390LutLo<>(SB), RODATA|NOPTR, $16

DATA ds390LutHi<>+0(SB)/1, $0x10
DATA ds390LutHi<>+1(SB)/1, $0x10
DATA ds390LutHi<>+2(SB)/1, $0x01
DATA ds390LutHi<>+3(SB)/1, $0x02
DATA ds390LutHi<>+4(SB)/1, $0x04
DATA ds390LutHi<>+5(SB)/1, $0x08
DATA ds390LutHi<>+6(SB)/1, $0x04
DATA ds390LutHi<>+7(SB)/1, $0x08
DATA ds390LutHi<>+8(SB)/1, $0x10
DATA ds390LutHi<>+9(SB)/1, $0x10
DATA ds390LutHi<>+10(SB)/1, $0x10
DATA ds390LutHi<>+11(SB)/1, $0x10
DATA ds390LutHi<>+12(SB)/1, $0x10
DATA ds390LutHi<>+13(SB)/1, $0x10
DATA ds390LutHi<>+14(SB)/1, $0x10
DATA ds390LutHi<>+15(SB)/1, $0x10
GLOBL ds390LutHi<>(SB), RODATA|NOPTR, $16

DATA ds390LutRoll<>+0(SB)/1, $0x00
DATA ds390LutRoll<>+1(SB)/1, $0x10
DATA ds390LutRoll<>+2(SB)/1, $0x13
DATA ds390LutRoll<>+3(SB)/1, $0x04
DATA ds390LutRoll<>+4(SB)/1, $0xbf
DATA ds390LutRoll<>+5(SB)/1, $0xbf
DATA ds390LutRoll<>+6(SB)/1, $0xb9
DATA ds390LutRoll<>+7(SB)/1, $0xb9
DATA ds390LutRoll<>+8(SB)/1, $0x00
DATA ds390LutRoll<>+9(SB)/1, $0x00
DATA ds390LutRoll<>+10(SB)/1, $0x00
DATA ds390LutRoll<>+11(SB)/1, $0x00
DATA ds390LutRoll<>+12(SB)/1, $0x00
DATA ds390LutRoll<>+13(SB)/1, $0x00
DATA ds390LutRoll<>+14(SB)/1, $0x00
DATA ds390LutRoll<>+15(SB)/1, $0x00
GLOBL ds390LutRoll<>(SB), RODATA|NOPTR, $16

DATA ds390M0<>+0(SB)/1, $0x00
DATA ds390M0<>+1(SB)/1, $0xfc
DATA ds390M0<>+2(SB)/1, $0x00
DATA ds390M0<>+3(SB)/1, $0x00
DATA ds390M0<>+4(SB)/1, $0x00
DATA ds390M0<>+5(SB)/1, $0xfc
DATA ds390M0<>+6(SB)/1, $0x00
DATA ds390M0<>+7(SB)/1, $0x00
DATA ds390M0<>+8(SB)/1, $0x00
DATA ds390M0<>+9(SB)/1, $0xfc
DATA ds390M0<>+10(SB)/1, $0x00
DATA ds390M0<>+11(SB)/1, $0x00
DATA ds390M0<>+12(SB)/1, $0x00
DATA ds390M0<>+13(SB)/1, $0xfc
DATA ds390M0<>+14(SB)/1, $0x00
DATA ds390M0<>+15(SB)/1, $0x00
GLOBL ds390M0<>(SB), RODATA|NOPTR, $16

DATA ds390M1<>+0(SB)/1, $0x00
DATA ds390M1<>+1(SB)/1, $0x03
DATA ds390M1<>+2(SB)/1, $0xf0
DATA ds390M1<>+3(SB)/1, $0x00
DATA ds390M1<>+4(SB)/1, $0x00
DATA ds390M1<>+5(SB)/1, $0x03
DATA ds390M1<>+6(SB)/1, $0xf0
DATA ds390M1<>+7(SB)/1, $0x00
DATA ds390M1<>+8(SB)/1, $0x00
DATA ds390M1<>+9(SB)/1, $0x03
DATA ds390M1<>+10(SB)/1, $0xf0
DATA ds390M1<>+11(SB)/1, $0x00
DATA ds390M1<>+12(SB)/1, $0x00
DATA ds390M1<>+13(SB)/1, $0x03
DATA ds390M1<>+14(SB)/1, $0xf0
DATA ds390M1<>+15(SB)/1, $0x00
GLOBL ds390M1<>(SB), RODATA|NOPTR, $16

DATA ds390M2<>+0(SB)/1, $0x00
DATA ds390M2<>+1(SB)/1, $0x00
DATA ds390M2<>+2(SB)/1, $0x0f
DATA ds390M2<>+3(SB)/1, $0xc0
DATA ds390M2<>+4(SB)/1, $0x00
DATA ds390M2<>+5(SB)/1, $0x00
DATA ds390M2<>+6(SB)/1, $0x0f
DATA ds390M2<>+7(SB)/1, $0xc0
DATA ds390M2<>+8(SB)/1, $0x00
DATA ds390M2<>+9(SB)/1, $0x00
DATA ds390M2<>+10(SB)/1, $0x0f
DATA ds390M2<>+11(SB)/1, $0xc0
DATA ds390M2<>+12(SB)/1, $0x00
DATA ds390M2<>+13(SB)/1, $0x00
DATA ds390M2<>+14(SB)/1, $0x0f
DATA ds390M2<>+15(SB)/1, $0xc0
GLOBL ds390M2<>(SB), RODATA|NOPTR, $16

DATA ds390M3<>+0(SB)/1, $0x00
DATA ds390M3<>+1(SB)/1, $0x00
DATA ds390M3<>+2(SB)/1, $0x00
DATA ds390M3<>+3(SB)/1, $0x3f
DATA ds390M3<>+4(SB)/1, $0x00
DATA ds390M3<>+5(SB)/1, $0x00
DATA ds390M3<>+6(SB)/1, $0x00
DATA ds390M3<>+7(SB)/1, $0x3f
DATA ds390M3<>+8(SB)/1, $0x00
DATA ds390M3<>+9(SB)/1, $0x00
DATA ds390M3<>+10(SB)/1, $0x00
DATA ds390M3<>+11(SB)/1, $0x3f
DATA ds390M3<>+12(SB)/1, $0x00
DATA ds390M3<>+13(SB)/1, $0x00
DATA ds390M3<>+14(SB)/1, $0x00
DATA ds390M3<>+15(SB)/1, $0x3f
GLOBL ds390M3<>(SB), RODATA|NOPTR, $16

DATA ds390C0f<>+0(SB)/1, $0x0f
DATA ds390C0f<>+1(SB)/1, $0x0f
DATA ds390C0f<>+2(SB)/1, $0x0f
DATA ds390C0f<>+3(SB)/1, $0x0f
DATA ds390C0f<>+4(SB)/1, $0x0f
DATA ds390C0f<>+5(SB)/1, $0x0f
DATA ds390C0f<>+6(SB)/1, $0x0f
DATA ds390C0f<>+7(SB)/1, $0x0f
DATA ds390C0f<>+8(SB)/1, $0x0f
DATA ds390C0f<>+9(SB)/1, $0x0f
DATA ds390C0f<>+10(SB)/1, $0x0f
DATA ds390C0f<>+11(SB)/1, $0x0f
DATA ds390C0f<>+12(SB)/1, $0x0f
DATA ds390C0f<>+13(SB)/1, $0x0f
DATA ds390C0f<>+14(SB)/1, $0x0f
DATA ds390C0f<>+15(SB)/1, $0x0f
GLOBL ds390C0f<>(SB), RODATA|NOPTR, $16

DATA ds390C2f<>+0(SB)/1, $0x2f
DATA ds390C2f<>+1(SB)/1, $0x2f
DATA ds390C2f<>+2(SB)/1, $0x2f
DATA ds390C2f<>+3(SB)/1, $0x2f
DATA ds390C2f<>+4(SB)/1, $0x2f
DATA ds390C2f<>+5(SB)/1, $0x2f
DATA ds390C2f<>+6(SB)/1, $0x2f
DATA ds390C2f<>+7(SB)/1, $0x2f
DATA ds390C2f<>+8(SB)/1, $0x2f
DATA ds390C2f<>+9(SB)/1, $0x2f
DATA ds390C2f<>+10(SB)/1, $0x2f
DATA ds390C2f<>+11(SB)/1, $0x2f
DATA ds390C2f<>+12(SB)/1, $0x2f
DATA ds390C2f<>+13(SB)/1, $0x2f
DATA ds390C2f<>+14(SB)/1, $0x2f
DATA ds390C2f<>+15(SB)/1, $0x2f
GLOBL ds390C2f<>(SB), RODATA|NOPTR, $16

DATA ds390Pshuf<>+0(SB)/1, $0x01
DATA ds390Pshuf<>+1(SB)/1, $0x02
DATA ds390Pshuf<>+2(SB)/1, $0x03
DATA ds390Pshuf<>+3(SB)/1, $0x05
DATA ds390Pshuf<>+4(SB)/1, $0x06
DATA ds390Pshuf<>+5(SB)/1, $0x07
DATA ds390Pshuf<>+6(SB)/1, $0x09
DATA ds390Pshuf<>+7(SB)/1, $0x0a
DATA ds390Pshuf<>+8(SB)/1, $0x0b
DATA ds390Pshuf<>+9(SB)/1, $0x0d
DATA ds390Pshuf<>+10(SB)/1, $0x0e
DATA ds390Pshuf<>+11(SB)/1, $0x0f
DATA ds390Pshuf<>+12(SB)/1, $0x00
DATA ds390Pshuf<>+13(SB)/1, $0x00
DATA ds390Pshuf<>+14(SB)/1, $0x00
DATA ds390Pshuf<>+15(SB)/1, $0x00
GLOBL ds390Pshuf<>(SB), RODATA|NOPTR, $16

