//go:build ppc64le

package base64

// decodeBlocks decodes up to n groups of 16 base64 chars into 12 bytes each via
// the VSX/AltiVec vector facility (Lemire/Muła vectorised decode). It returns the
// number of groups fully decoded before running out of groups or hitting a block
// that contains an invalid base64 byte (whitespace, padding '=', or any non-
// alphabet char); the caller decodes the remainder with the stdlib. Generated by
// go-asmgen (decode_ppc64x_gen.go), in decode_ppc64x.s. It emits ISA-3.0 (POWER9)
// instructions (LXVB16X/STXVB16X) that SIGILL on POWER8, so callers must gate it
// behind hasVSX (cpu.PPC64.IsPOWER9; declared in encode_ppc64le.go).
// decodeBlocksURL is the identical kernel with the -_ alphabet's translate LUTs.
func decodeBlocks(dst, src []byte, n int) int
func decodeBlocksURL(dst, src []byte, n int) int

// decodeSIMD decodes the clean leading blocks of src and reports bytes
// consumed/written so the caller finishes the tail (the padded final quantum, or
// the first block with an invalid byte) with the stdlib. The kernel reads 16
// bytes and stores 16 per 12-byte group while advancing dst by 12, so it
// over-writes 4 bytes past each group; we reserve an 8-byte trailing source span
// (where StdEncoding padding also lives) so the final group's over-store stays in
// the room the scalar tail decode needs.
// On a pre-POWER9 CPU it reports no progress so the whole input goes to the stdlib.
// url selects the -_ (URL/RawURL) alphabet kernel over the +/ one.
// The caller (Decode) guarantees len(src) >= decodeSIMDMin (16+8); only a
// pre-POWER9 CPU (no VSX) sends the work to the stdlib instead.
func decodeSIMD(dst, src []byte, url bool) (srcDone, dstDone int) {
	n := len(src)
	if !hasVSX {
		return 0, 0
	}
	usable := n - 8
	groups := usable / 16
	var got int
	if url {
		got = decodeBlocksURL(dst, src, groups)
	} else {
		got = decodeBlocks(dst, src, groups)
	}
	return got * 16, got * 12
}
