//go:build arm64

package base64

// decodeBlocks decodes up to n blocks of 64 base64 chars into 48 bytes each via
// NEON, using the aklomp/emmansun deinterleaving-I/O design: a VLD4.P load
// splits the input into its four char-planes, a two-table VTBL+VTBX translate
// maps each char to its 6-bit value (and flags invalid bytes), the 4x6-bit ->
// 3-byte pack is pure shifts, and a VST3.P interleaving store writes the bytes
// back in order. It returns the number of 64-char blocks fully decoded before
// running out of blocks or hitting a block that contains an invalid base64 byte
// (whitespace, padding '=', or any non-alphabet char); the caller decodes the
// remainder with the stdlib. Generated by go-asmgen (decode_arm64_gen.go), in
// decode_arm64.s.
func decodeBlocks(dst, src []byte, n int) int

// decodeSIMD decodes the clean leading 64-char blocks of src and reports bytes
// consumed/written so the caller finishes the tail (the padded final quantum, or
// the first block with an invalid byte) with the stdlib. VLD4.P reads exactly 64
// chars and VST3.P writes exactly 48 bytes per block — no over-read or
// over-store — so no trailing source span needs to be reserved; the kernel
// self-limits at the first block containing padding or any invalid byte, which
// the stdlib then re-decodes for byte- and offset-identical results.
func decodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	blocks := len(src) / 64
	if blocks == 0 {
		return 0, 0
	}
	got := decodeBlocks(dst, src, blocks)
	return got * 64, got * 48
}
