//go:build s390x

package base64

// encodeBlocks encodes n groups of 12 input bytes into 16 base64 chars each, via
// the z/Architecture vector facility (Lemire/Muła vectorised base64). Generated by
// go-asmgen (encode_s390x_gen.go), in encode_s390x.s.
func encodeBlocks(dst, src []byte, n int)

// encodeSIMD runs encodeBlocks over the part of src where a 16-byte VL load stays
// in bounds (it reads 16 bytes per 12-byte group), reporting bytes consumed in src
// and written in dst so the caller can finish the tail with the stdlib.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if n < 16 {
		return 0, 0
	}
	groups := (n-16)/12 + 1
	encodeBlocks(dst, src, groups)
	return groups * 12, groups * 16
}
