// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·encodeBlocks(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R2
	MOVD $alpha<>(SB), R3
	VLD1 (R3), [V8.B16, V9.B16, V10.B16, V11.B16]
	MOVD $0x3f, R4
	VDUP R4, V7.B16
	CBZ R2, done
loop:
	VLD3.P 48(R1), [V0.B16, V1.B16, V2.B16]
	VUSHR $2, V0.B16, V3.B16
	VUSHR $4, V1.B16, V4.B16
	VUSHR $6, V2.B16, V5.B16
	VSLI $4, V0.B16, V4.B16
	VSLI $2, V1.B16, V5.B16
	VAND V7.B16, V4.B16, V4.B16
	VAND V7.B16, V5.B16, V5.B16
	VAND V7.B16, V2.B16, V6.B16
	VTBL V3.B16, [V8.B16, V9.B16, V10.B16, V11.B16], V3.B16
	VTBL V4.B16, [V8.B16, V9.B16, V10.B16, V11.B16], V4.B16
	VTBL V5.B16, [V8.B16, V9.B16, V10.B16, V11.B16], V5.B16
	VTBL V6.B16, [V8.B16, V9.B16, V10.B16, V11.B16], V6.B16
	VST4.P [V3.B16, V4.B16, V5.B16, V6.B16], 64(R0)
	SUB $1, R2
	CBNZ R2, loop
done:
	RET

TEXT ·encodeBlocksURL(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R2
	MOVD $alphaURL<>(SB), R3
	VLD1 (R3), [V8.B16, V9.B16, V10.B16, V11.B16]
	MOVD $0x3f, R4
	VDUP R4, V7.B16
	CBZ R2, done
loop:
	VLD3.P 48(R1), [V0.B16, V1.B16, V2.B16]
	VUSHR $2, V0.B16, V3.B16
	VUSHR $4, V1.B16, V4.B16
	VUSHR $6, V2.B16, V5.B16
	VSLI $4, V0.B16, V4.B16
	VSLI $2, V1.B16, V5.B16
	VAND V7.B16, V4.B16, V4.B16
	VAND V7.B16, V5.B16, V5.B16
	VAND V7.B16, V2.B16, V6.B16
	VTBL V3.B16, [V8.B16, V9.B16, V10.B16, V11.B16], V3.B16
	VTBL V4.B16, [V8.B16, V9.B16, V10.B16, V11.B16], V4.B16
	VTBL V5.B16, [V8.B16, V9.B16, V10.B16, V11.B16], V5.B16
	VTBL V6.B16, [V8.B16, V9.B16, V10.B16, V11.B16], V6.B16
	VST4.P [V3.B16, V4.B16, V5.B16, V6.B16], 64(R0)
	SUB $1, R2
	CBNZ R2, loop
done:
	RET

DATA alpha<>+0(SB)/1, $0x41
DATA alpha<>+1(SB)/1, $0x42
DATA alpha<>+2(SB)/1, $0x43
DATA alpha<>+3(SB)/1, $0x44
DATA alpha<>+4(SB)/1, $0x45
DATA alpha<>+5(SB)/1, $0x46
DATA alpha<>+6(SB)/1, $0x47
DATA alpha<>+7(SB)/1, $0x48
DATA alpha<>+8(SB)/1, $0x49
DATA alpha<>+9(SB)/1, $0x4a
DATA alpha<>+10(SB)/1, $0x4b
DATA alpha<>+11(SB)/1, $0x4c
DATA alpha<>+12(SB)/1, $0x4d
DATA alpha<>+13(SB)/1, $0x4e
DATA alpha<>+14(SB)/1, $0x4f
DATA alpha<>+15(SB)/1, $0x50
DATA alpha<>+16(SB)/1, $0x51
DATA alpha<>+17(SB)/1, $0x52
DATA alpha<>+18(SB)/1, $0x53
DATA alpha<>+19(SB)/1, $0x54
DATA alpha<>+20(SB)/1, $0x55
DATA alpha<>+21(SB)/1, $0x56
DATA alpha<>+22(SB)/1, $0x57
DATA alpha<>+23(SB)/1, $0x58
DATA alpha<>+24(SB)/1, $0x59
DATA alpha<>+25(SB)/1, $0x5a
DATA alpha<>+26(SB)/1, $0x61
DATA alpha<>+27(SB)/1, $0x62
DATA alpha<>+28(SB)/1, $0x63
DATA alpha<>+29(SB)/1, $0x64
DATA alpha<>+30(SB)/1, $0x65
DATA alpha<>+31(SB)/1, $0x66
DATA alpha<>+32(SB)/1, $0x67
DATA alpha<>+33(SB)/1, $0x68
DATA alpha<>+34(SB)/1, $0x69
DATA alpha<>+35(SB)/1, $0x6a
DATA alpha<>+36(SB)/1, $0x6b
DATA alpha<>+37(SB)/1, $0x6c
DATA alpha<>+38(SB)/1, $0x6d
DATA alpha<>+39(SB)/1, $0x6e
DATA alpha<>+40(SB)/1, $0x6f
DATA alpha<>+41(SB)/1, $0x70
DATA alpha<>+42(SB)/1, $0x71
DATA alpha<>+43(SB)/1, $0x72
DATA alpha<>+44(SB)/1, $0x73
DATA alpha<>+45(SB)/1, $0x74
DATA alpha<>+46(SB)/1, $0x75
DATA alpha<>+47(SB)/1, $0x76
DATA alpha<>+48(SB)/1, $0x77
DATA alpha<>+49(SB)/1, $0x78
DATA alpha<>+50(SB)/1, $0x79
DATA alpha<>+51(SB)/1, $0x7a
DATA alpha<>+52(SB)/1, $0x30
DATA alpha<>+53(SB)/1, $0x31
DATA alpha<>+54(SB)/1, $0x32
DATA alpha<>+55(SB)/1, $0x33
DATA alpha<>+56(SB)/1, $0x34
DATA alpha<>+57(SB)/1, $0x35
DATA alpha<>+58(SB)/1, $0x36
DATA alpha<>+59(SB)/1, $0x37
DATA alpha<>+60(SB)/1, $0x38
DATA alpha<>+61(SB)/1, $0x39
DATA alpha<>+62(SB)/1, $0x2b
DATA alpha<>+63(SB)/1, $0x2f
GLOBL alpha<>(SB), RODATA|NOPTR, $64

DATA alphaURL<>+0(SB)/1, $0x41
DATA alphaURL<>+1(SB)/1, $0x42
DATA alphaURL<>+2(SB)/1, $0x43
DATA alphaURL<>+3(SB)/1, $0x44
DATA alphaURL<>+4(SB)/1, $0x45
DATA alphaURL<>+5(SB)/1, $0x46
DATA alphaURL<>+6(SB)/1, $0x47
DATA alphaURL<>+7(SB)/1, $0x48
DATA alphaURL<>+8(SB)/1, $0x49
DATA alphaURL<>+9(SB)/1, $0x4a
DATA alphaURL<>+10(SB)/1, $0x4b
DATA alphaURL<>+11(SB)/1, $0x4c
DATA alphaURL<>+12(SB)/1, $0x4d
DATA alphaURL<>+13(SB)/1, $0x4e
DATA alphaURL<>+14(SB)/1, $0x4f
DATA alphaURL<>+15(SB)/1, $0x50
DATA alphaURL<>+16(SB)/1, $0x51
DATA alphaURL<>+17(SB)/1, $0x52
DATA alphaURL<>+18(SB)/1, $0x53
DATA alphaURL<>+19(SB)/1, $0x54
DATA alphaURL<>+20(SB)/1, $0x55
DATA alphaURL<>+21(SB)/1, $0x56
DATA alphaURL<>+22(SB)/1, $0x57
DATA alphaURL<>+23(SB)/1, $0x58
DATA alphaURL<>+24(SB)/1, $0x59
DATA alphaURL<>+25(SB)/1, $0x5a
DATA alphaURL<>+26(SB)/1, $0x61
DATA alphaURL<>+27(SB)/1, $0x62
DATA alphaURL<>+28(SB)/1, $0x63
DATA alphaURL<>+29(SB)/1, $0x64
DATA alphaURL<>+30(SB)/1, $0x65
DATA alphaURL<>+31(SB)/1, $0x66
DATA alphaURL<>+32(SB)/1, $0x67
DATA alphaURL<>+33(SB)/1, $0x68
DATA alphaURL<>+34(SB)/1, $0x69
DATA alphaURL<>+35(SB)/1, $0x6a
DATA alphaURL<>+36(SB)/1, $0x6b
DATA alphaURL<>+37(SB)/1, $0x6c
DATA alphaURL<>+38(SB)/1, $0x6d
DATA alphaURL<>+39(SB)/1, $0x6e
DATA alphaURL<>+40(SB)/1, $0x6f
DATA alphaURL<>+41(SB)/1, $0x70
DATA alphaURL<>+42(SB)/1, $0x71
DATA alphaURL<>+43(SB)/1, $0x72
DATA alphaURL<>+44(SB)/1, $0x73
DATA alphaURL<>+45(SB)/1, $0x74
DATA alphaURL<>+46(SB)/1, $0x75
DATA alphaURL<>+47(SB)/1, $0x76
DATA alphaURL<>+48(SB)/1, $0x77
DATA alphaURL<>+49(SB)/1, $0x78
DATA alphaURL<>+50(SB)/1, $0x79
DATA alphaURL<>+51(SB)/1, $0x7a
DATA alphaURL<>+52(SB)/1, $0x30
DATA alphaURL<>+53(SB)/1, $0x31
DATA alphaURL<>+54(SB)/1, $0x32
DATA alphaURL<>+55(SB)/1, $0x33
DATA alphaURL<>+56(SB)/1, $0x34
DATA alphaURL<>+57(SB)/1, $0x35
DATA alphaURL<>+58(SB)/1, $0x36
DATA alphaURL<>+59(SB)/1, $0x37
DATA alphaURL<>+60(SB)/1, $0x38
DATA alphaURL<>+61(SB)/1, $0x39
DATA alphaURL<>+62(SB)/1, $0x2d
DATA alphaURL<>+63(SB)/1, $0x5f
GLOBL alphaURL<>(SB), RODATA|NOPTR, $64

