// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·encodeBlocks(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	MOVOU shuf<>+0(SB), X7
	MOVOU mask1<>+0(SB), X8
	MOVOU mulhi<>+0(SB), X9
	MOVOU mask2<>+0(SB), X10
	MOVOU mullo<>+0(SB), X11
	MOVOU c51<>+0(SB), X12
	MOVOU c25<>+0(SB), X13
	MOVOU lut<>+0(SB), X14
	TESTQ CX, CX
	JZ done
loop:
	MOVOU (SI), X0
	PSHUFB X7, X0
	MOVO X0, X1
	PAND X8, X1
	PMULHUW X9, X1
	MOVO X0, X2
	PAND X10, X2
	PMULLW X11, X2
	POR X2, X1
	MOVO X1, X3
	PSUBUSB X12, X3
	MOVO X1, X4
	PCMPGTB X13, X4
	PSUBB X4, X3
	MOVO X14, X5
	PSHUFB X3, X5
	PADDB X1, X5
	MOVOU X5, (DI)
	ADDQ $12, SI
	ADDQ $16, DI
	DECQ CX
	JNZ loop
done:
	RET

DATA shuf<>+0(SB)/1, $0x01
DATA shuf<>+1(SB)/1, $0x00
DATA shuf<>+2(SB)/1, $0x02
DATA shuf<>+3(SB)/1, $0x01
DATA shuf<>+4(SB)/1, $0x04
DATA shuf<>+5(SB)/1, $0x03
DATA shuf<>+6(SB)/1, $0x05
DATA shuf<>+7(SB)/1, $0x04
DATA shuf<>+8(SB)/1, $0x07
DATA shuf<>+9(SB)/1, $0x06
DATA shuf<>+10(SB)/1, $0x08
DATA shuf<>+11(SB)/1, $0x07
DATA shuf<>+12(SB)/1, $0x0a
DATA shuf<>+13(SB)/1, $0x09
DATA shuf<>+14(SB)/1, $0x0b
DATA shuf<>+15(SB)/1, $0x0a
GLOBL shuf<>(SB), RODATA|NOPTR, $16

DATA mask1<>+0(SB)/1, $0x00
DATA mask1<>+1(SB)/1, $0xfc
DATA mask1<>+2(SB)/1, $0xc0
DATA mask1<>+3(SB)/1, $0x0f
DATA mask1<>+4(SB)/1, $0x00
DATA mask1<>+5(SB)/1, $0xfc
DATA mask1<>+6(SB)/1, $0xc0
DATA mask1<>+7(SB)/1, $0x0f
DATA mask1<>+8(SB)/1, $0x00
DATA mask1<>+9(SB)/1, $0xfc
DATA mask1<>+10(SB)/1, $0xc0
DATA mask1<>+11(SB)/1, $0x0f
DATA mask1<>+12(SB)/1, $0x00
DATA mask1<>+13(SB)/1, $0xfc
DATA mask1<>+14(SB)/1, $0xc0
DATA mask1<>+15(SB)/1, $0x0f
GLOBL mask1<>(SB), RODATA|NOPTR, $16

DATA mulhi<>+0(SB)/1, $0x40
DATA mulhi<>+1(SB)/1, $0x00
DATA mulhi<>+2(SB)/1, $0x00
DATA mulhi<>+3(SB)/1, $0x04
DATA mulhi<>+4(SB)/1, $0x40
DATA mulhi<>+5(SB)/1, $0x00
DATA mulhi<>+6(SB)/1, $0x00
DATA mulhi<>+7(SB)/1, $0x04
DATA mulhi<>+8(SB)/1, $0x40
DATA mulhi<>+9(SB)/1, $0x00
DATA mulhi<>+10(SB)/1, $0x00
DATA mulhi<>+11(SB)/1, $0x04
DATA mulhi<>+12(SB)/1, $0x40
DATA mulhi<>+13(SB)/1, $0x00
DATA mulhi<>+14(SB)/1, $0x00
DATA mulhi<>+15(SB)/1, $0x04
GLOBL mulhi<>(SB), RODATA|NOPTR, $16

DATA mask2<>+0(SB)/1, $0xf0
DATA mask2<>+1(SB)/1, $0x03
DATA mask2<>+2(SB)/1, $0x3f
DATA mask2<>+3(SB)/1, $0x00
DATA mask2<>+4(SB)/1, $0xf0
DATA mask2<>+5(SB)/1, $0x03
DATA mask2<>+6(SB)/1, $0x3f
DATA mask2<>+7(SB)/1, $0x00
DATA mask2<>+8(SB)/1, $0xf0
DATA mask2<>+9(SB)/1, $0x03
DATA mask2<>+10(SB)/1, $0x3f
DATA mask2<>+11(SB)/1, $0x00
DATA mask2<>+12(SB)/1, $0xf0
DATA mask2<>+13(SB)/1, $0x03
DATA mask2<>+14(SB)/1, $0x3f
DATA mask2<>+15(SB)/1, $0x00
GLOBL mask2<>(SB), RODATA|NOPTR, $16

DATA mullo<>+0(SB)/1, $0x10
DATA mullo<>+1(SB)/1, $0x00
DATA mullo<>+2(SB)/1, $0x00
DATA mullo<>+3(SB)/1, $0x01
DATA mullo<>+4(SB)/1, $0x10
DATA mullo<>+5(SB)/1, $0x00
DATA mullo<>+6(SB)/1, $0x00
DATA mullo<>+7(SB)/1, $0x01
DATA mullo<>+8(SB)/1, $0x10
DATA mullo<>+9(SB)/1, $0x00
DATA mullo<>+10(SB)/1, $0x00
DATA mullo<>+11(SB)/1, $0x01
DATA mullo<>+12(SB)/1, $0x10
DATA mullo<>+13(SB)/1, $0x00
DATA mullo<>+14(SB)/1, $0x00
DATA mullo<>+15(SB)/1, $0x01
GLOBL mullo<>(SB), RODATA|NOPTR, $16

DATA c51<>+0(SB)/1, $0x33
DATA c51<>+1(SB)/1, $0x33
DATA c51<>+2(SB)/1, $0x33
DATA c51<>+3(SB)/1, $0x33
DATA c51<>+4(SB)/1, $0x33
DATA c51<>+5(SB)/1, $0x33
DATA c51<>+6(SB)/1, $0x33
DATA c51<>+7(SB)/1, $0x33
DATA c51<>+8(SB)/1, $0x33
DATA c51<>+9(SB)/1, $0x33
DATA c51<>+10(SB)/1, $0x33
DATA c51<>+11(SB)/1, $0x33
DATA c51<>+12(SB)/1, $0x33
DATA c51<>+13(SB)/1, $0x33
DATA c51<>+14(SB)/1, $0x33
DATA c51<>+15(SB)/1, $0x33
GLOBL c51<>(SB), RODATA|NOPTR, $16

DATA c25<>+0(SB)/1, $0x19
DATA c25<>+1(SB)/1, $0x19
DATA c25<>+2(SB)/1, $0x19
DATA c25<>+3(SB)/1, $0x19
DATA c25<>+4(SB)/1, $0x19
DATA c25<>+5(SB)/1, $0x19
DATA c25<>+6(SB)/1, $0x19
DATA c25<>+7(SB)/1, $0x19
DATA c25<>+8(SB)/1, $0x19
DATA c25<>+9(SB)/1, $0x19
DATA c25<>+10(SB)/1, $0x19
DATA c25<>+11(SB)/1, $0x19
DATA c25<>+12(SB)/1, $0x19
DATA c25<>+13(SB)/1, $0x19
DATA c25<>+14(SB)/1, $0x19
DATA c25<>+15(SB)/1, $0x19
GLOBL c25<>(SB), RODATA|NOPTR, $16

DATA lut<>+0(SB)/1, $0x41
DATA lut<>+1(SB)/1, $0x47
DATA lut<>+2(SB)/1, $0xfc
DATA lut<>+3(SB)/1, $0xfc
DATA lut<>+4(SB)/1, $0xfc
DATA lut<>+5(SB)/1, $0xfc
DATA lut<>+6(SB)/1, $0xfc
DATA lut<>+7(SB)/1, $0xfc
DATA lut<>+8(SB)/1, $0xfc
DATA lut<>+9(SB)/1, $0xfc
DATA lut<>+10(SB)/1, $0xfc
DATA lut<>+11(SB)/1, $0xfc
DATA lut<>+12(SB)/1, $0xed
DATA lut<>+13(SB)/1, $0xf0
DATA lut<>+14(SB)/1, $0x00
DATA lut<>+15(SB)/1, $0x00
GLOBL lut<>(SB), RODATA|NOPTR, $16

