// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64

#include "textflag.h"

TEXT ·encodeBlocks(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R2
	MOVD $shuf<>(SB), R3
	VLD1 (R3), [V7.B16]
	MOVD $m0<>(SB), R3
	VLD1 (R3), [V8.B16]
	MOVD $m1a<>(SB), R3
	VLD1 (R3), [V9.B16]
	MOVD $m1b<>(SB), R3
	VLD1 (R3), [V10.B16]
	MOVD $m2a<>(SB), R3
	VLD1 (R3), [V11.B16]
	MOVD $m2b<>(SB), R3
	VLD1 (R3), [V12.B16]
	MOVD $m3<>(SB), R3
	VLD1 (R3), [V13.B16]
	MOVD $lut<>(SB), R3
	VLD1 (R3), [V14.B16]
	VMOVI $51, V15.B16
	VMOVI $25, V16.B16
	VMOVI $1, V17.B16
	VMOVI $0, V18.B16
	CBZ R2, done
loop:
	VLD1 (R1), [V0.B16]
	VTBL V7.B16, [V0.B16], V0.B16
	VUSHR $10, V0.S4, V1.S4
	VAND V8.B16, V1.B16, V1.B16
	VSHL $4, V0.S4, V2.S4
	VAND V9.B16, V2.B16, V3.B16
	VAND V10.B16, V2.B16, V2.B16
	VORR V3.B16, V2.B16, V2.B16
	VORR V2.B16, V1.B16, V1.B16
	VSHL $18, V0.S4, V2.S4
	VAND V11.B16, V2.B16, V2.B16
	VUSHR $6, V0.S4, V3.S4
	VAND V12.B16, V3.B16, V3.B16
	VORR V3.B16, V2.B16, V2.B16
	VORR V2.B16, V1.B16, V1.B16
	VSHL $8, V0.S4, V2.S4
	VAND V13.B16, V2.B16, V2.B16
	VORR V2.B16, V1.B16, V1.B16
	VUMIN V15.B16, V1.B16, V2.B16
	VSUB V2.B16, V1.B16, V2.B16
	VUMIN V16.B16, V1.B16, V3.B16
	VSUB V3.B16, V1.B16, V3.B16
	VCMEQ V18.B16, V3.B16, V3.B16
	VEOR V17.B16, V3.B16, V3.B16
	VAND V17.B16, V3.B16, V3.B16
	VADD V3.B16, V2.B16, V2.B16
	VTBL V2.B16, [V14.B16], V2.B16
	VADD V1.B16, V2.B16, V2.B16
	VST1 [V2.B16], (R0)
	ADD $12, R1
	ADD $16, R0
	SUB $1, R2
	CBNZ R2, loop
done:
	RET

DATA shuf<>+0(SB)/1, $0x01
DATA shuf<>+1(SB)/1, $0x00
DATA shuf<>+2(SB)/1, $0x02
DATA shuf<>+3(SB)/1, $0x01
DATA shuf<>+4(SB)/1, $0x04
DATA shuf<>+5(SB)/1, $0x03
DATA shuf<>+6(SB)/1, $0x05
DATA shuf<>+7(SB)/1, $0x04
DATA shuf<>+8(SB)/1, $0x07
DATA shuf<>+9(SB)/1, $0x06
DATA shuf<>+10(SB)/1, $0x08
DATA shuf<>+11(SB)/1, $0x07
DATA shuf<>+12(SB)/1, $0x0a
DATA shuf<>+13(SB)/1, $0x09
DATA shuf<>+14(SB)/1, $0x0b
DATA shuf<>+15(SB)/1, $0x0a
GLOBL shuf<>(SB), RODATA|NOPTR, $16

DATA m0<>+0(SB)/1, $0x3f
DATA m0<>+1(SB)/1, $0x00
DATA m0<>+2(SB)/1, $0x00
DATA m0<>+3(SB)/1, $0x00
DATA m0<>+4(SB)/1, $0x3f
DATA m0<>+5(SB)/1, $0x00
DATA m0<>+6(SB)/1, $0x00
DATA m0<>+7(SB)/1, $0x00
DATA m0<>+8(SB)/1, $0x3f
DATA m0<>+9(SB)/1, $0x00
DATA m0<>+10(SB)/1, $0x00
DATA m0<>+11(SB)/1, $0x00
DATA m0<>+12(SB)/1, $0x3f
DATA m0<>+13(SB)/1, $0x00
DATA m0<>+14(SB)/1, $0x00
DATA m0<>+15(SB)/1, $0x00
GLOBL m0<>(SB), RODATA|NOPTR, $16

DATA m1a<>+0(SB)/1, $0x00
DATA m1a<>+1(SB)/1, $0x30
DATA m1a<>+2(SB)/1, $0x00
DATA m1a<>+3(SB)/1, $0x00
DATA m1a<>+4(SB)/1, $0x00
DATA m1a<>+5(SB)/1, $0x30
DATA m1a<>+6(SB)/1, $0x00
DATA m1a<>+7(SB)/1, $0x00
DATA m1a<>+8(SB)/1, $0x00
DATA m1a<>+9(SB)/1, $0x30
DATA m1a<>+10(SB)/1, $0x00
DATA m1a<>+11(SB)/1, $0x00
DATA m1a<>+12(SB)/1, $0x00
DATA m1a<>+13(SB)/1, $0x30
DATA m1a<>+14(SB)/1, $0x00
DATA m1a<>+15(SB)/1, $0x00
GLOBL m1a<>(SB), RODATA|NOPTR, $16

DATA m1b<>+0(SB)/1, $0x00
DATA m1b<>+1(SB)/1, $0x0f
DATA m1b<>+2(SB)/1, $0x00
DATA m1b<>+3(SB)/1, $0x00
DATA m1b<>+4(SB)/1, $0x00
DATA m1b<>+5(SB)/1, $0x0f
DATA m1b<>+6(SB)/1, $0x00
DATA m1b<>+7(SB)/1, $0x00
DATA m1b<>+8(SB)/1, $0x00
DATA m1b<>+9(SB)/1, $0x0f
DATA m1b<>+10(SB)/1, $0x00
DATA m1b<>+11(SB)/1, $0x00
DATA m1b<>+12(SB)/1, $0x00
DATA m1b<>+13(SB)/1, $0x0f
DATA m1b<>+14(SB)/1, $0x00
DATA m1b<>+15(SB)/1, $0x00
GLOBL m1b<>(SB), RODATA|NOPTR, $16

DATA m2a<>+0(SB)/1, $0x00
DATA m2a<>+1(SB)/1, $0x00
DATA m2a<>+2(SB)/1, $0x3c
DATA m2a<>+3(SB)/1, $0x00
DATA m2a<>+4(SB)/1, $0x00
DATA m2a<>+5(SB)/1, $0x00
DATA m2a<>+6(SB)/1, $0x3c
DATA m2a<>+7(SB)/1, $0x00
DATA m2a<>+8(SB)/1, $0x00
DATA m2a<>+9(SB)/1, $0x00
DATA m2a<>+10(SB)/1, $0x3c
DATA m2a<>+11(SB)/1, $0x00
DATA m2a<>+12(SB)/1, $0x00
DATA m2a<>+13(SB)/1, $0x00
DATA m2a<>+14(SB)/1, $0x3c
DATA m2a<>+15(SB)/1, $0x00
GLOBL m2a<>(SB), RODATA|NOPTR, $16

DATA m2b<>+0(SB)/1, $0x00
DATA m2b<>+1(SB)/1, $0x00
DATA m2b<>+2(SB)/1, $0x03
DATA m2b<>+3(SB)/1, $0x00
DATA m2b<>+4(SB)/1, $0x00
DATA m2b<>+5(SB)/1, $0x00
DATA m2b<>+6(SB)/1, $0x03
DATA m2b<>+7(SB)/1, $0x00
DATA m2b<>+8(SB)/1, $0x00
DATA m2b<>+9(SB)/1, $0x00
DATA m2b<>+10(SB)/1, $0x03
DATA m2b<>+11(SB)/1, $0x00
DATA m2b<>+12(SB)/1, $0x00
DATA m2b<>+13(SB)/1, $0x00
DATA m2b<>+14(SB)/1, $0x03
DATA m2b<>+15(SB)/1, $0x00
GLOBL m2b<>(SB), RODATA|NOPTR, $16

DATA m3<>+0(SB)/1, $0x00
DATA m3<>+1(SB)/1, $0x00
DATA m3<>+2(SB)/1, $0x00
DATA m3<>+3(SB)/1, $0x3f
DATA m3<>+4(SB)/1, $0x00
DATA m3<>+5(SB)/1, $0x00
DATA m3<>+6(SB)/1, $0x00
DATA m3<>+7(SB)/1, $0x3f
DATA m3<>+8(SB)/1, $0x00
DATA m3<>+9(SB)/1, $0x00
DATA m3<>+10(SB)/1, $0x00
DATA m3<>+11(SB)/1, $0x3f
DATA m3<>+12(SB)/1, $0x00
DATA m3<>+13(SB)/1, $0x00
DATA m3<>+14(SB)/1, $0x00
DATA m3<>+15(SB)/1, $0x3f
GLOBL m3<>(SB), RODATA|NOPTR, $16

DATA lut<>+0(SB)/1, $0x41
DATA lut<>+1(SB)/1, $0x47
DATA lut<>+2(SB)/1, $0xfc
DATA lut<>+3(SB)/1, $0xfc
DATA lut<>+4(SB)/1, $0xfc
DATA lut<>+5(SB)/1, $0xfc
DATA lut<>+6(SB)/1, $0xfc
DATA lut<>+7(SB)/1, $0xfc
DATA lut<>+8(SB)/1, $0xfc
DATA lut<>+9(SB)/1, $0xfc
DATA lut<>+10(SB)/1, $0xfc
DATA lut<>+11(SB)/1, $0xfc
DATA lut<>+12(SB)/1, $0xed
DATA lut<>+13(SB)/1, $0xf0
DATA lut<>+14(SB)/1, $0x00
DATA lut<>+15(SB)/1, $0x00
GLOBL lut<>(SB), RODATA|NOPTR, $16

