//go:build amd64

package base64

import "golang.org/x/sys/cpu"

// encodeBlocksSSE (12 bytes -> 16 chars) and encodeBlocksAVX2 (24 -> 32) are the
// vectorised base64 encoders. Generated by go-asmgen (encode_gen.go), in
// encode_amd64.s.
func encodeBlocksSSE(dst, src []byte, n int)
func encodeBlocksAVX2(dst, src []byte, n int)

var hasAVX2 = cpu.X86.HasAVX2

// encodeSIMD runs the widest available kernel over the part of src where its
// over-reading load stays in bounds, reporting bytes consumed/written so the
// caller finishes the tail. AVX2 reads 32 bytes per 24-byte group; SSE reads 16
// per 12.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if hasAVX2 && n >= 32 {
		groups := (n-32)/24 + 1
		encodeBlocksAVX2(dst, src, groups)
		return groups * 24, groups * 32
	}
	if n >= 16 {
		groups := (n-16)/12 + 1
		encodeBlocksSSE(dst, src, groups)
		return groups * 12, groups * 16
	}
	return 0, 0
}
