//go:build arm64

package base64

// encodeBlocks encodes n blocks of 48 input bytes into 64 base64 chars each via
// NEON, using the aklomp/emmansun deinterleaving-I/O design: a VLD3.P
// deinterleaving load splits the input into its three byte-planes, the four
// 6-bit indices per 24-bit group are extracted with shifts and inserts (no
// integer vector multiply, so it runs on the released arm64 assembler), four
// VTBL lookups map them through the alphabet, and a VST4.P interleaving store
// writes the chars back in order. Generated by go-asmgen (encode_arm64_gen.go),
// in encode_arm64.s.
func encodeBlocks(dst, src []byte, n int)

// encodeSIMD runs encodeBlocks over as many whole 48-byte input blocks as fit in
// src (each block is read and written exactly, no over-read), and reports the
// bytes consumed in src and written in dst so the caller can finish the tail.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	blocks := len(src) / 48
	if blocks == 0 {
		return 0, 0
	}
	encodeBlocks(dst, src, blocks)
	return blocks * 48, blocks * 64
}
