//go:build amd64

package base64

// encodeBlocks encodes n groups of 12 input bytes into 16 base64 chars each, via
// SSE2/SSSE3 (Lemire's vectorised base64). Generated by go-asmgen
// (encode_gen.go), in encode_amd64.s.
func encodeBlocks(dst, src []byte, n int)

// encodeSIMD runs encodeBlocks over the part of src where a 16-byte load stays in
// bounds (it reads 16 bytes per 12-byte group), and reports the bytes consumed in
// src and written in dst so the caller can finish the tail.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if n < 16 {
		return 0, 0
	}
	groups := (n-16)/12 + 1
	encodeBlocks(dst, src, groups)
	return groups * 12, groups * 16
}
