// Code generated by go-asmgen. DO NOT EDIT.

//go:build arm64 && go1.27

#include "textflag.h"

TEXT ·encodeBlocks(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R0
	MOVD src_base+24(FP), R1
	MOVD n+48(FP), R2
	MOVD $shuf<>(SB), R3
	VLD1 (R3), [V3.B16]
	MOVD $mask1<>(SB), R3
	VLD1 (R3), [V4.B16]
	MOVD $mask2<>(SB), R3
	VLD1 (R3), [V5.B16]
	MOVD $hiext<>(SB), R3
	VLD1 (R3), [V6.B16]
	MOVD $alpha<>(SB), R3
	VLD1 (R3), [V8.B16, V9.B16, V10.B16, V11.B16]
	MOVD $0x01000010, R4
	VDUP R4, V7.S4
	VSHL $2, V7.S4, V12.S4
	CBZ R2, done
loop:
	VLD1 (R1), [V0.B16]
	VTBL V3.B16, [V0.B16], V0.B16
	VAND V4.B16, V0.B16, V2.B16
	VUMULL V12.H4, V2.H4, V1.S4
	VUMULL2 V12.H8, V2.H8, V2.S4
	VTBL V6.B16, [V1.B16, V2.B16], V1.B16
	VAND V5.B16, V0.B16, V0.B16
	VMUL V7.H8, V0.H8, V0.H8
	VORR V0.B16, V1.B16, V0.B16
	VTBL V0.B16, [V8.B16, V9.B16, V10.B16, V11.B16], V0.B16
	VST1 [V0.B16], (R0)
	ADD $12, R1
	ADD $16, R0
	SUB $1, R2
	CBNZ R2, loop
done:
	RET

DATA shuf<>+0(SB)/1, $0x01
DATA shuf<>+1(SB)/1, $0x00
DATA shuf<>+2(SB)/1, $0x02
DATA shuf<>+3(SB)/1, $0x01
DATA shuf<>+4(SB)/1, $0x04
DATA shuf<>+5(SB)/1, $0x03
DATA shuf<>+6(SB)/1, $0x05
DATA shuf<>+7(SB)/1, $0x04
DATA shuf<>+8(SB)/1, $0x07
DATA shuf<>+9(SB)/1, $0x06
DATA shuf<>+10(SB)/1, $0x08
DATA shuf<>+11(SB)/1, $0x07
DATA shuf<>+12(SB)/1, $0x0a
DATA shuf<>+13(SB)/1, $0x09
DATA shuf<>+14(SB)/1, $0x0b
DATA shuf<>+15(SB)/1, $0x0a
GLOBL shuf<>(SB), RODATA|NOPTR, $16

DATA mask1<>+0(SB)/1, $0x00
DATA mask1<>+1(SB)/1, $0xfc
DATA mask1<>+2(SB)/1, $0xc0
DATA mask1<>+3(SB)/1, $0x0f
DATA mask1<>+4(SB)/1, $0x00
DATA mask1<>+5(SB)/1, $0xfc
DATA mask1<>+6(SB)/1, $0xc0
DATA mask1<>+7(SB)/1, $0x0f
DATA mask1<>+8(SB)/1, $0x00
DATA mask1<>+9(SB)/1, $0xfc
DATA mask1<>+10(SB)/1, $0xc0
DATA mask1<>+11(SB)/1, $0x0f
DATA mask1<>+12(SB)/1, $0x00
DATA mask1<>+13(SB)/1, $0xfc
DATA mask1<>+14(SB)/1, $0xc0
DATA mask1<>+15(SB)/1, $0x0f
GLOBL mask1<>(SB), RODATA|NOPTR, $16

DATA mask2<>+0(SB)/1, $0xf0
DATA mask2<>+1(SB)/1, $0x03
DATA mask2<>+2(SB)/1, $0x3f
DATA mask2<>+3(SB)/1, $0x00
DATA mask2<>+4(SB)/1, $0xf0
DATA mask2<>+5(SB)/1, $0x03
DATA mask2<>+6(SB)/1, $0x3f
DATA mask2<>+7(SB)/1, $0x00
DATA mask2<>+8(SB)/1, $0xf0
DATA mask2<>+9(SB)/1, $0x03
DATA mask2<>+10(SB)/1, $0x3f
DATA mask2<>+11(SB)/1, $0x00
DATA mask2<>+12(SB)/1, $0xf0
DATA mask2<>+13(SB)/1, $0x03
DATA mask2<>+14(SB)/1, $0x3f
DATA mask2<>+15(SB)/1, $0x00
GLOBL mask2<>(SB), RODATA|NOPTR, $16

DATA hiext<>+0(SB)/1, $0x02
DATA hiext<>+1(SB)/1, $0x03
DATA hiext<>+2(SB)/1, $0x06
DATA hiext<>+3(SB)/1, $0x07
DATA hiext<>+4(SB)/1, $0x0a
DATA hiext<>+5(SB)/1, $0x0b
DATA hiext<>+6(SB)/1, $0x0e
DATA hiext<>+7(SB)/1, $0x0f
DATA hiext<>+8(SB)/1, $0x12
DATA hiext<>+9(SB)/1, $0x13
DATA hiext<>+10(SB)/1, $0x16
DATA hiext<>+11(SB)/1, $0x17
DATA hiext<>+12(SB)/1, $0x1a
DATA hiext<>+13(SB)/1, $0x1b
DATA hiext<>+14(SB)/1, $0x1e
DATA hiext<>+15(SB)/1, $0x1f
GLOBL hiext<>(SB), RODATA|NOPTR, $16

DATA alpha<>+0(SB)/1, $0x41
DATA alpha<>+1(SB)/1, $0x42
DATA alpha<>+2(SB)/1, $0x43
DATA alpha<>+3(SB)/1, $0x44
DATA alpha<>+4(SB)/1, $0x45
DATA alpha<>+5(SB)/1, $0x46
DATA alpha<>+6(SB)/1, $0x47
DATA alpha<>+7(SB)/1, $0x48
DATA alpha<>+8(SB)/1, $0x49
DATA alpha<>+9(SB)/1, $0x4a
DATA alpha<>+10(SB)/1, $0x4b
DATA alpha<>+11(SB)/1, $0x4c
DATA alpha<>+12(SB)/1, $0x4d
DATA alpha<>+13(SB)/1, $0x4e
DATA alpha<>+14(SB)/1, $0x4f
DATA alpha<>+15(SB)/1, $0x50
DATA alpha<>+16(SB)/1, $0x51
DATA alpha<>+17(SB)/1, $0x52
DATA alpha<>+18(SB)/1, $0x53
DATA alpha<>+19(SB)/1, $0x54
DATA alpha<>+20(SB)/1, $0x55
DATA alpha<>+21(SB)/1, $0x56
DATA alpha<>+22(SB)/1, $0x57
DATA alpha<>+23(SB)/1, $0x58
DATA alpha<>+24(SB)/1, $0x59
DATA alpha<>+25(SB)/1, $0x5a
DATA alpha<>+26(SB)/1, $0x61
DATA alpha<>+27(SB)/1, $0x62
DATA alpha<>+28(SB)/1, $0x63
DATA alpha<>+29(SB)/1, $0x64
DATA alpha<>+30(SB)/1, $0x65
DATA alpha<>+31(SB)/1, $0x66
DATA alpha<>+32(SB)/1, $0x67
DATA alpha<>+33(SB)/1, $0x68
DATA alpha<>+34(SB)/1, $0x69
DATA alpha<>+35(SB)/1, $0x6a
DATA alpha<>+36(SB)/1, $0x6b
DATA alpha<>+37(SB)/1, $0x6c
DATA alpha<>+38(SB)/1, $0x6d
DATA alpha<>+39(SB)/1, $0x6e
DATA alpha<>+40(SB)/1, $0x6f
DATA alpha<>+41(SB)/1, $0x70
DATA alpha<>+42(SB)/1, $0x71
DATA alpha<>+43(SB)/1, $0x72
DATA alpha<>+44(SB)/1, $0x73
DATA alpha<>+45(SB)/1, $0x74
DATA alpha<>+46(SB)/1, $0x75
DATA alpha<>+47(SB)/1, $0x76
DATA alpha<>+48(SB)/1, $0x77
DATA alpha<>+49(SB)/1, $0x78
DATA alpha<>+50(SB)/1, $0x79
DATA alpha<>+51(SB)/1, $0x7a
DATA alpha<>+52(SB)/1, $0x30
DATA alpha<>+53(SB)/1, $0x31
DATA alpha<>+54(SB)/1, $0x32
DATA alpha<>+55(SB)/1, $0x33
DATA alpha<>+56(SB)/1, $0x34
DATA alpha<>+57(SB)/1, $0x35
DATA alpha<>+58(SB)/1, $0x36
DATA alpha<>+59(SB)/1, $0x37
DATA alpha<>+60(SB)/1, $0x38
DATA alpha<>+61(SB)/1, $0x39
DATA alpha<>+62(SB)/1, $0x2b
DATA alpha<>+63(SB)/1, $0x2f
GLOBL alpha<>(SB), RODATA|NOPTR, $64

