//go:build s390x

package base64

// encodeSIMDMin / decodeSIMDMin are the smallest inputs the s390x kernels touch
// (16 src bytes to encode, 16+8 chars to decode). Below them Encode/Decode hand
// straight to the stdlib so a tiny input is never slower than encoding/base64.
const (
	encodeSIMDMin = 16
	decodeSIMDMin = 16 + 8
)

// encodeBlocks encodes n groups of 12 input bytes into 16 base64 chars each, via
// the z/Architecture vector facility (Lemire/Muła vectorised base64). Generated by
// go-asmgen (encode_s390x_gen.go), in encode_s390x.s. encodeBlocksURL is the
// identical kernel with the -_ ASCII offset-LUT (only two entries differ).
func encodeBlocks(dst, src []byte, n int)
func encodeBlocksURL(dst, src []byte, n int)

// encodeSIMD runs the encode kernel over the part of src where a 16-byte VL load
// stays in bounds (it reads 16 bytes per 12-byte group), reporting bytes consumed
// in src and written in dst so the caller can finish the tail with the stdlib. url
// selects the -_ (URL/RawURL) alphabet kernel over the +/ one.
// The caller (Encode) guarantees len(src) >= encodeSIMDMin (16), so groups >= 1.
func encodeSIMD(dst, src []byte, url bool) (srcDone, dstDone int) {
	n := len(src)
	groups := (n-16)/12 + 1
	if url {
		encodeBlocksURL(dst, src, groups)
	} else {
		encodeBlocks(dst, src, groups)
	}
	return groups * 12, groups * 16
}
