//go:build arm64 && go1.27

package base64

// encodeBlocks encodes n groups of 12 input bytes into 16 base64 chars each via
// NEON, using the integer multiply (VUMULL/VUMULL2/VMUL) the Go arm64 assembler
// only gained in Go 1.27 — the Lemire/Muła 6-bit-index extraction (the NEON
// analogue of the SSE PMULHUW/PMULLW path in encode_amd64.s). Generated by
// go-asmgen (encode_arm64_go127_gen.go) into encode_arm64_go127.s. The stable
// build (encode_arm64.go) keeps a shift-and-mask kernel that needs no multiply.
func encodeBlocks(dst, src []byte, n int)

// encodeSIMD runs encodeBlocks over the part of src where a 16-byte load stays in
// bounds (it reads 16 bytes per 12-byte group), and reports the bytes consumed in
// src and written in dst so the caller can finish the tail.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if n < 16 {
		return 0, 0
	}
	groups := (n-16)/12 + 1
	encodeBlocks(dst, src, groups)
	return groups * 12, groups * 16
}
