//go:build arm64 && !go1.27

package base64

// encodeBlocks encodes n groups of 12 input bytes into 16 base64 chars each, via
// NEON (Lemire/Muła vectorised base64). This is the stable-Go path: it extracts
// the four 6-bit indices with per-lane shifts and masks because released Go's
// arm64 assembler has no integer vector multiply. The go1.27 build replaces it
// with a VUMULL/VMUL multiply kernel (encode_arm64_go127.go). Generated by
// go-asmgen (encode_arm64_gen.go), in encode_arm64.s.
func encodeBlocks(dst, src []byte, n int)

// encodeSIMD runs encodeBlocks over the part of src where a 16-byte load stays in
// bounds (it reads 16 bytes per 12-byte group), and reports the bytes consumed in
// src and written in dst so the caller can finish the tail.
func encodeSIMD(dst, src []byte) (srcDone, dstDone int) {
	n := len(src)
	if n < 16 {
		return 0, 0
	}
	groups := (n-16)/12 + 1
	encodeBlocks(dst, src, groups)
	return groups * 12, groups * 16
}
