// Code generated by go-asmgen. DO NOT EDIT.

//go:build amd64

#include "textflag.h"

TEXT ·encodeBlocksSSE(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	MOVOU shuf<>+0(SB), X7
	MOVOU mask1<>+0(SB), X8
	MOVOU mulhi<>+0(SB), X9
	MOVOU mask2<>+0(SB), X10
	MOVOU mullo<>+0(SB), X11
	MOVOU c51<>+0(SB), X12
	MOVOU c25<>+0(SB), X13
	MOVOU lut<>+0(SB), X14
	TESTQ CX, CX
	JZ sdone
sloop:
	MOVOU (SI), X0
	PSHUFB X7, X0
	MOVO X0, X1
	PAND X8, X1
	PMULHUW X9, X1
	MOVO X0, X2
	PAND X10, X2
	PMULLW X11, X2
	POR X2, X1
	MOVO X1, X3
	PSUBUSB X12, X3
	MOVO X1, X4
	PCMPGTB X13, X4
	PSUBB X4, X3
	MOVO X14, X5
	PSHUFB X3, X5
	PADDB X1, X5
	MOVOU X5, (DI)
	ADDQ $12, SI
	ADDQ $16, DI
	DECQ CX
	JNZ sloop
sdone:
	RET

TEXT ·encodeBlocksAVX2(SB), NOSPLIT, $0-56
	MOVQ dst_base+0(FP), DI
	MOVQ src_base+24(FP), SI
	MOVQ n+48(FP), CX
	VMOVDQU shuf2<>+0(SB), Y8
	VMOVDQU mask1b<>+0(SB), Y9
	VMOVDQU mulhib<>+0(SB), Y10
	VMOVDQU mask2b<>+0(SB), Y11
	VMOVDQU mullob<>+0(SB), Y12
	VMOVDQU c51b<>+0(SB), Y13
	VMOVDQU c25b<>+0(SB), Y14
	VMOVDQU lutb<>+0(SB), Y15
vpair:
	CMPQ CX, $2
	JLT vsingle
	VMOVDQU (SI), Y0
	VINSERTI128 $1, 12(SI), Y0, Y0
	VMOVDQU 24(SI), Y3
	VINSERTI128 $1, 36(SI), Y3, Y3
	VPSHUFB Y8, Y0, Y0
	VPSHUFB Y8, Y3, Y3
	VPAND Y9, Y0, Y1
	VPMULHUW Y10, Y1, Y1
	VPAND Y9, Y3, Y4
	VPMULHUW Y10, Y4, Y4
	VPAND Y11, Y0, Y2
	VPMULLW Y12, Y2, Y2
	VPAND Y11, Y3, Y5
	VPMULLW Y12, Y5, Y5
	VPOR Y2, Y1, Y1
	VPOR Y5, Y4, Y4
	VPSUBUSB Y13, Y1, Y0
	VPSUBUSB Y13, Y4, Y3
	VPCMPGTB Y14, Y1, Y2
	VPCMPGTB Y14, Y4, Y5
	VPSUBB Y2, Y0, Y0
	VPSUBB Y5, Y3, Y3
	VPSHUFB Y0, Y15, Y0
	VPSHUFB Y3, Y15, Y3
	VPADDB Y1, Y0, Y1
	VPADDB Y4, Y3, Y4
	VMOVDQU Y1, (DI)
	VMOVDQU Y4, 32(DI)
	ADDQ $48, SI
	ADDQ $64, DI
	SUBQ $2, CX
	JMP vpair
vsingle:
	TESTQ CX, CX
	JZ vdone
	VMOVDQU (SI), Y0
	VINSERTI128 $1, 12(SI), Y0, Y0
	VPSHUFB Y8, Y0, Y0
	VPAND Y9, Y0, Y1
	VPMULHUW Y10, Y1, Y1
	VPAND Y11, Y0, Y2
	VPMULLW Y12, Y2, Y2
	VPOR Y2, Y1, Y1
	VPSUBUSB Y13, Y1, Y3
	VPCMPGTB Y14, Y1, Y4
	VPSUBB Y4, Y3, Y3
	VPSHUFB Y3, Y15, Y5
	VPADDB Y1, Y5, Y5
	VMOVDQU Y5, (DI)
vdone:
	VZEROUPPER
	RET

DATA shuf<>+0(SB)/1, $0x01
DATA shuf<>+1(SB)/1, $0x00
DATA shuf<>+2(SB)/1, $0x02
DATA shuf<>+3(SB)/1, $0x01
DATA shuf<>+4(SB)/1, $0x04
DATA shuf<>+5(SB)/1, $0x03
DATA shuf<>+6(SB)/1, $0x05
DATA shuf<>+7(SB)/1, $0x04
DATA shuf<>+8(SB)/1, $0x07
DATA shuf<>+9(SB)/1, $0x06
DATA shuf<>+10(SB)/1, $0x08
DATA shuf<>+11(SB)/1, $0x07
DATA shuf<>+12(SB)/1, $0x0a
DATA shuf<>+13(SB)/1, $0x09
DATA shuf<>+14(SB)/1, $0x0b
DATA shuf<>+15(SB)/1, $0x0a
GLOBL shuf<>(SB), RODATA|NOPTR, $16

DATA mask1<>+0(SB)/1, $0x00
DATA mask1<>+1(SB)/1, $0xfc
DATA mask1<>+2(SB)/1, $0xc0
DATA mask1<>+3(SB)/1, $0x0f
DATA mask1<>+4(SB)/1, $0x00
DATA mask1<>+5(SB)/1, $0xfc
DATA mask1<>+6(SB)/1, $0xc0
DATA mask1<>+7(SB)/1, $0x0f
DATA mask1<>+8(SB)/1, $0x00
DATA mask1<>+9(SB)/1, $0xfc
DATA mask1<>+10(SB)/1, $0xc0
DATA mask1<>+11(SB)/1, $0x0f
DATA mask1<>+12(SB)/1, $0x00
DATA mask1<>+13(SB)/1, $0xfc
DATA mask1<>+14(SB)/1, $0xc0
DATA mask1<>+15(SB)/1, $0x0f
GLOBL mask1<>(SB), RODATA|NOPTR, $16

DATA mulhi<>+0(SB)/1, $0x40
DATA mulhi<>+1(SB)/1, $0x00
DATA mulhi<>+2(SB)/1, $0x00
DATA mulhi<>+3(SB)/1, $0x04
DATA mulhi<>+4(SB)/1, $0x40
DATA mulhi<>+5(SB)/1, $0x00
DATA mulhi<>+6(SB)/1, $0x00
DATA mulhi<>+7(SB)/1, $0x04
DATA mulhi<>+8(SB)/1, $0x40
DATA mulhi<>+9(SB)/1, $0x00
DATA mulhi<>+10(SB)/1, $0x00
DATA mulhi<>+11(SB)/1, $0x04
DATA mulhi<>+12(SB)/1, $0x40
DATA mulhi<>+13(SB)/1, $0x00
DATA mulhi<>+14(SB)/1, $0x00
DATA mulhi<>+15(SB)/1, $0x04
GLOBL mulhi<>(SB), RODATA|NOPTR, $16

DATA mask2<>+0(SB)/1, $0xf0
DATA mask2<>+1(SB)/1, $0x03
DATA mask2<>+2(SB)/1, $0x3f
DATA mask2<>+3(SB)/1, $0x00
DATA mask2<>+4(SB)/1, $0xf0
DATA mask2<>+5(SB)/1, $0x03
DATA mask2<>+6(SB)/1, $0x3f
DATA mask2<>+7(SB)/1, $0x00
DATA mask2<>+8(SB)/1, $0xf0
DATA mask2<>+9(SB)/1, $0x03
DATA mask2<>+10(SB)/1, $0x3f
DATA mask2<>+11(SB)/1, $0x00
DATA mask2<>+12(SB)/1, $0xf0
DATA mask2<>+13(SB)/1, $0x03
DATA mask2<>+14(SB)/1, $0x3f
DATA mask2<>+15(SB)/1, $0x00
GLOBL mask2<>(SB), RODATA|NOPTR, $16

DATA mullo<>+0(SB)/1, $0x10
DATA mullo<>+1(SB)/1, $0x00
DATA mullo<>+2(SB)/1, $0x00
DATA mullo<>+3(SB)/1, $0x01
DATA mullo<>+4(SB)/1, $0x10
DATA mullo<>+5(SB)/1, $0x00
DATA mullo<>+6(SB)/1, $0x00
DATA mullo<>+7(SB)/1, $0x01
DATA mullo<>+8(SB)/1, $0x10
DATA mullo<>+9(SB)/1, $0x00
DATA mullo<>+10(SB)/1, $0x00
DATA mullo<>+11(SB)/1, $0x01
DATA mullo<>+12(SB)/1, $0x10
DATA mullo<>+13(SB)/1, $0x00
DATA mullo<>+14(SB)/1, $0x00
DATA mullo<>+15(SB)/1, $0x01
GLOBL mullo<>(SB), RODATA|NOPTR, $16

DATA c51<>+0(SB)/1, $0x33
DATA c51<>+1(SB)/1, $0x33
DATA c51<>+2(SB)/1, $0x33
DATA c51<>+3(SB)/1, $0x33
DATA c51<>+4(SB)/1, $0x33
DATA c51<>+5(SB)/1, $0x33
DATA c51<>+6(SB)/1, $0x33
DATA c51<>+7(SB)/1, $0x33
DATA c51<>+8(SB)/1, $0x33
DATA c51<>+9(SB)/1, $0x33
DATA c51<>+10(SB)/1, $0x33
DATA c51<>+11(SB)/1, $0x33
DATA c51<>+12(SB)/1, $0x33
DATA c51<>+13(SB)/1, $0x33
DATA c51<>+14(SB)/1, $0x33
DATA c51<>+15(SB)/1, $0x33
GLOBL c51<>(SB), RODATA|NOPTR, $16

DATA c25<>+0(SB)/1, $0x19
DATA c25<>+1(SB)/1, $0x19
DATA c25<>+2(SB)/1, $0x19
DATA c25<>+3(SB)/1, $0x19
DATA c25<>+4(SB)/1, $0x19
DATA c25<>+5(SB)/1, $0x19
DATA c25<>+6(SB)/1, $0x19
DATA c25<>+7(SB)/1, $0x19
DATA c25<>+8(SB)/1, $0x19
DATA c25<>+9(SB)/1, $0x19
DATA c25<>+10(SB)/1, $0x19
DATA c25<>+11(SB)/1, $0x19
DATA c25<>+12(SB)/1, $0x19
DATA c25<>+13(SB)/1, $0x19
DATA c25<>+14(SB)/1, $0x19
DATA c25<>+15(SB)/1, $0x19
GLOBL c25<>(SB), RODATA|NOPTR, $16

DATA lut<>+0(SB)/1, $0x41
DATA lut<>+1(SB)/1, $0x47
DATA lut<>+2(SB)/1, $0xfc
DATA lut<>+3(SB)/1, $0xfc
DATA lut<>+4(SB)/1, $0xfc
DATA lut<>+5(SB)/1, $0xfc
DATA lut<>+6(SB)/1, $0xfc
DATA lut<>+7(SB)/1, $0xfc
DATA lut<>+8(SB)/1, $0xfc
DATA lut<>+9(SB)/1, $0xfc
DATA lut<>+10(SB)/1, $0xfc
DATA lut<>+11(SB)/1, $0xfc
DATA lut<>+12(SB)/1, $0xed
DATA lut<>+13(SB)/1, $0xf0
DATA lut<>+14(SB)/1, $0x00
DATA lut<>+15(SB)/1, $0x00
GLOBL lut<>(SB), RODATA|NOPTR, $16

DATA shuf2<>+0(SB)/1, $0x01
DATA shuf2<>+1(SB)/1, $0x00
DATA shuf2<>+2(SB)/1, $0x02
DATA shuf2<>+3(SB)/1, $0x01
DATA shuf2<>+4(SB)/1, $0x04
DATA shuf2<>+5(SB)/1, $0x03
DATA shuf2<>+6(SB)/1, $0x05
DATA shuf2<>+7(SB)/1, $0x04
DATA shuf2<>+8(SB)/1, $0x07
DATA shuf2<>+9(SB)/1, $0x06
DATA shuf2<>+10(SB)/1, $0x08
DATA shuf2<>+11(SB)/1, $0x07
DATA shuf2<>+12(SB)/1, $0x0a
DATA shuf2<>+13(SB)/1, $0x09
DATA shuf2<>+14(SB)/1, $0x0b
DATA shuf2<>+15(SB)/1, $0x0a
DATA shuf2<>+16(SB)/1, $0x01
DATA shuf2<>+17(SB)/1, $0x00
DATA shuf2<>+18(SB)/1, $0x02
DATA shuf2<>+19(SB)/1, $0x01
DATA shuf2<>+20(SB)/1, $0x04
DATA shuf2<>+21(SB)/1, $0x03
DATA shuf2<>+22(SB)/1, $0x05
DATA shuf2<>+23(SB)/1, $0x04
DATA shuf2<>+24(SB)/1, $0x07
DATA shuf2<>+25(SB)/1, $0x06
DATA shuf2<>+26(SB)/1, $0x08
DATA shuf2<>+27(SB)/1, $0x07
DATA shuf2<>+28(SB)/1, $0x0a
DATA shuf2<>+29(SB)/1, $0x09
DATA shuf2<>+30(SB)/1, $0x0b
DATA shuf2<>+31(SB)/1, $0x0a
GLOBL shuf2<>(SB), RODATA|NOPTR, $32

DATA mask1b<>+0(SB)/1, $0x00
DATA mask1b<>+1(SB)/1, $0xfc
DATA mask1b<>+2(SB)/1, $0xc0
DATA mask1b<>+3(SB)/1, $0x0f
DATA mask1b<>+4(SB)/1, $0x00
DATA mask1b<>+5(SB)/1, $0xfc
DATA mask1b<>+6(SB)/1, $0xc0
DATA mask1b<>+7(SB)/1, $0x0f
DATA mask1b<>+8(SB)/1, $0x00
DATA mask1b<>+9(SB)/1, $0xfc
DATA mask1b<>+10(SB)/1, $0xc0
DATA mask1b<>+11(SB)/1, $0x0f
DATA mask1b<>+12(SB)/1, $0x00
DATA mask1b<>+13(SB)/1, $0xfc
DATA mask1b<>+14(SB)/1, $0xc0
DATA mask1b<>+15(SB)/1, $0x0f
DATA mask1b<>+16(SB)/1, $0x00
DATA mask1b<>+17(SB)/1, $0xfc
DATA mask1b<>+18(SB)/1, $0xc0
DATA mask1b<>+19(SB)/1, $0x0f
DATA mask1b<>+20(SB)/1, $0x00
DATA mask1b<>+21(SB)/1, $0xfc
DATA mask1b<>+22(SB)/1, $0xc0
DATA mask1b<>+23(SB)/1, $0x0f
DATA mask1b<>+24(SB)/1, $0x00
DATA mask1b<>+25(SB)/1, $0xfc
DATA mask1b<>+26(SB)/1, $0xc0
DATA mask1b<>+27(SB)/1, $0x0f
DATA mask1b<>+28(SB)/1, $0x00
DATA mask1b<>+29(SB)/1, $0xfc
DATA mask1b<>+30(SB)/1, $0xc0
DATA mask1b<>+31(SB)/1, $0x0f
GLOBL mask1b<>(SB), RODATA|NOPTR, $32

DATA mulhib<>+0(SB)/1, $0x40
DATA mulhib<>+1(SB)/1, $0x00
DATA mulhib<>+2(SB)/1, $0x00
DATA mulhib<>+3(SB)/1, $0x04
DATA mulhib<>+4(SB)/1, $0x40
DATA mulhib<>+5(SB)/1, $0x00
DATA mulhib<>+6(SB)/1, $0x00
DATA mulhib<>+7(SB)/1, $0x04
DATA mulhib<>+8(SB)/1, $0x40
DATA mulhib<>+9(SB)/1, $0x00
DATA mulhib<>+10(SB)/1, $0x00
DATA mulhib<>+11(SB)/1, $0x04
DATA mulhib<>+12(SB)/1, $0x40
DATA mulhib<>+13(SB)/1, $0x00
DATA mulhib<>+14(SB)/1, $0x00
DATA mulhib<>+15(SB)/1, $0x04
DATA mulhib<>+16(SB)/1, $0x40
DATA mulhib<>+17(SB)/1, $0x00
DATA mulhib<>+18(SB)/1, $0x00
DATA mulhib<>+19(SB)/1, $0x04
DATA mulhib<>+20(SB)/1, $0x40
DATA mulhib<>+21(SB)/1, $0x00
DATA mulhib<>+22(SB)/1, $0x00
DATA mulhib<>+23(SB)/1, $0x04
DATA mulhib<>+24(SB)/1, $0x40
DATA mulhib<>+25(SB)/1, $0x00
DATA mulhib<>+26(SB)/1, $0x00
DATA mulhib<>+27(SB)/1, $0x04
DATA mulhib<>+28(SB)/1, $0x40
DATA mulhib<>+29(SB)/1, $0x00
DATA mulhib<>+30(SB)/1, $0x00
DATA mulhib<>+31(SB)/1, $0x04
GLOBL mulhib<>(SB), RODATA|NOPTR, $32

DATA mask2b<>+0(SB)/1, $0xf0
DATA mask2b<>+1(SB)/1, $0x03
DATA mask2b<>+2(SB)/1, $0x3f
DATA mask2b<>+3(SB)/1, $0x00
DATA mask2b<>+4(SB)/1, $0xf0
DATA mask2b<>+5(SB)/1, $0x03
DATA mask2b<>+6(SB)/1, $0x3f
DATA mask2b<>+7(SB)/1, $0x00
DATA mask2b<>+8(SB)/1, $0xf0
DATA mask2b<>+9(SB)/1, $0x03
DATA mask2b<>+10(SB)/1, $0x3f
DATA mask2b<>+11(SB)/1, $0x00
DATA mask2b<>+12(SB)/1, $0xf0
DATA mask2b<>+13(SB)/1, $0x03
DATA mask2b<>+14(SB)/1, $0x3f
DATA mask2b<>+15(SB)/1, $0x00
DATA mask2b<>+16(SB)/1, $0xf0
DATA mask2b<>+17(SB)/1, $0x03
DATA mask2b<>+18(SB)/1, $0x3f
DATA mask2b<>+19(SB)/1, $0x00
DATA mask2b<>+20(SB)/1, $0xf0
DATA mask2b<>+21(SB)/1, $0x03
DATA mask2b<>+22(SB)/1, $0x3f
DATA mask2b<>+23(SB)/1, $0x00
DATA mask2b<>+24(SB)/1, $0xf0
DATA mask2b<>+25(SB)/1, $0x03
DATA mask2b<>+26(SB)/1, $0x3f
DATA mask2b<>+27(SB)/1, $0x00
DATA mask2b<>+28(SB)/1, $0xf0
DATA mask2b<>+29(SB)/1, $0x03
DATA mask2b<>+30(SB)/1, $0x3f
DATA mask2b<>+31(SB)/1, $0x00
GLOBL mask2b<>(SB), RODATA|NOPTR, $32

DATA mullob<>+0(SB)/1, $0x10
DATA mullob<>+1(SB)/1, $0x00
DATA mullob<>+2(SB)/1, $0x00
DATA mullob<>+3(SB)/1, $0x01
DATA mullob<>+4(SB)/1, $0x10
DATA mullob<>+5(SB)/1, $0x00
DATA mullob<>+6(SB)/1, $0x00
DATA mullob<>+7(SB)/1, $0x01
DATA mullob<>+8(SB)/1, $0x10
DATA mullob<>+9(SB)/1, $0x00
DATA mullob<>+10(SB)/1, $0x00
DATA mullob<>+11(SB)/1, $0x01
DATA mullob<>+12(SB)/1, $0x10
DATA mullob<>+13(SB)/1, $0x00
DATA mullob<>+14(SB)/1, $0x00
DATA mullob<>+15(SB)/1, $0x01
DATA mullob<>+16(SB)/1, $0x10
DATA mullob<>+17(SB)/1, $0x00
DATA mullob<>+18(SB)/1, $0x00
DATA mullob<>+19(SB)/1, $0x01
DATA mullob<>+20(SB)/1, $0x10
DATA mullob<>+21(SB)/1, $0x00
DATA mullob<>+22(SB)/1, $0x00
DATA mullob<>+23(SB)/1, $0x01
DATA mullob<>+24(SB)/1, $0x10
DATA mullob<>+25(SB)/1, $0x00
DATA mullob<>+26(SB)/1, $0x00
DATA mullob<>+27(SB)/1, $0x01
DATA mullob<>+28(SB)/1, $0x10
DATA mullob<>+29(SB)/1, $0x00
DATA mullob<>+30(SB)/1, $0x00
DATA mullob<>+31(SB)/1, $0x01
GLOBL mullob<>(SB), RODATA|NOPTR, $32

DATA c51b<>+0(SB)/1, $0x33
DATA c51b<>+1(SB)/1, $0x33
DATA c51b<>+2(SB)/1, $0x33
DATA c51b<>+3(SB)/1, $0x33
DATA c51b<>+4(SB)/1, $0x33
DATA c51b<>+5(SB)/1, $0x33
DATA c51b<>+6(SB)/1, $0x33
DATA c51b<>+7(SB)/1, $0x33
DATA c51b<>+8(SB)/1, $0x33
DATA c51b<>+9(SB)/1, $0x33
DATA c51b<>+10(SB)/1, $0x33
DATA c51b<>+11(SB)/1, $0x33
DATA c51b<>+12(SB)/1, $0x33
DATA c51b<>+13(SB)/1, $0x33
DATA c51b<>+14(SB)/1, $0x33
DATA c51b<>+15(SB)/1, $0x33
DATA c51b<>+16(SB)/1, $0x33
DATA c51b<>+17(SB)/1, $0x33
DATA c51b<>+18(SB)/1, $0x33
DATA c51b<>+19(SB)/1, $0x33
DATA c51b<>+20(SB)/1, $0x33
DATA c51b<>+21(SB)/1, $0x33
DATA c51b<>+22(SB)/1, $0x33
DATA c51b<>+23(SB)/1, $0x33
DATA c51b<>+24(SB)/1, $0x33
DATA c51b<>+25(SB)/1, $0x33
DATA c51b<>+26(SB)/1, $0x33
DATA c51b<>+27(SB)/1, $0x33
DATA c51b<>+28(SB)/1, $0x33
DATA c51b<>+29(SB)/1, $0x33
DATA c51b<>+30(SB)/1, $0x33
DATA c51b<>+31(SB)/1, $0x33
GLOBL c51b<>(SB), RODATA|NOPTR, $32

DATA c25b<>+0(SB)/1, $0x19
DATA c25b<>+1(SB)/1, $0x19
DATA c25b<>+2(SB)/1, $0x19
DATA c25b<>+3(SB)/1, $0x19
DATA c25b<>+4(SB)/1, $0x19
DATA c25b<>+5(SB)/1, $0x19
DATA c25b<>+6(SB)/1, $0x19
DATA c25b<>+7(SB)/1, $0x19
DATA c25b<>+8(SB)/1, $0x19
DATA c25b<>+9(SB)/1, $0x19
DATA c25b<>+10(SB)/1, $0x19
DATA c25b<>+11(SB)/1, $0x19
DATA c25b<>+12(SB)/1, $0x19
DATA c25b<>+13(SB)/1, $0x19
DATA c25b<>+14(SB)/1, $0x19
DATA c25b<>+15(SB)/1, $0x19
DATA c25b<>+16(SB)/1, $0x19
DATA c25b<>+17(SB)/1, $0x19
DATA c25b<>+18(SB)/1, $0x19
DATA c25b<>+19(SB)/1, $0x19
DATA c25b<>+20(SB)/1, $0x19
DATA c25b<>+21(SB)/1, $0x19
DATA c25b<>+22(SB)/1, $0x19
DATA c25b<>+23(SB)/1, $0x19
DATA c25b<>+24(SB)/1, $0x19
DATA c25b<>+25(SB)/1, $0x19
DATA c25b<>+26(SB)/1, $0x19
DATA c25b<>+27(SB)/1, $0x19
DATA c25b<>+28(SB)/1, $0x19
DATA c25b<>+29(SB)/1, $0x19
DATA c25b<>+30(SB)/1, $0x19
DATA c25b<>+31(SB)/1, $0x19
GLOBL c25b<>(SB), RODATA|NOPTR, $32

DATA lutb<>+0(SB)/1, $0x41
DATA lutb<>+1(SB)/1, $0x47
DATA lutb<>+2(SB)/1, $0xfc
DATA lutb<>+3(SB)/1, $0xfc
DATA lutb<>+4(SB)/1, $0xfc
DATA lutb<>+5(SB)/1, $0xfc
DATA lutb<>+6(SB)/1, $0xfc
DATA lutb<>+7(SB)/1, $0xfc
DATA lutb<>+8(SB)/1, $0xfc
DATA lutb<>+9(SB)/1, $0xfc
DATA lutb<>+10(SB)/1, $0xfc
DATA lutb<>+11(SB)/1, $0xfc
DATA lutb<>+12(SB)/1, $0xed
DATA lutb<>+13(SB)/1, $0xf0
DATA lutb<>+14(SB)/1, $0x00
DATA lutb<>+15(SB)/1, $0x00
DATA lutb<>+16(SB)/1, $0x41
DATA lutb<>+17(SB)/1, $0x47
DATA lutb<>+18(SB)/1, $0xfc
DATA lutb<>+19(SB)/1, $0xfc
DATA lutb<>+20(SB)/1, $0xfc
DATA lutb<>+21(SB)/1, $0xfc
DATA lutb<>+22(SB)/1, $0xfc
DATA lutb<>+23(SB)/1, $0xfc
DATA lutb<>+24(SB)/1, $0xfc
DATA lutb<>+25(SB)/1, $0xfc
DATA lutb<>+26(SB)/1, $0xfc
DATA lutb<>+27(SB)/1, $0xfc
DATA lutb<>+28(SB)/1, $0xed
DATA lutb<>+29(SB)/1, $0xf0
DATA lutb<>+30(SB)/1, $0x00
DATA lutb<>+31(SB)/1, $0x00
GLOBL lutb<>(SB), RODATA|NOPTR, $32

