//go:build ppc64le

package base64

import "golang.org/x/sys/cpu"

// hasVSX gates the ppc64le VSX kernels (both encode and decode). The generated
// kernels emit ISA-3.0 (POWER9) instructions (LXVB16X/STXVB16X) that raise SIGILL
// on POWER8, so they run only when the CPU is POWER9+; on POWER8 encodeSIMD and
// decodeSIMD report no progress and the stdlib encoding/base64 path does all the
// work. It is a var (not a const) so the dispatch test can force the fallback.
var hasVSX = cpu.PPC64.IsPOWER9

// encodeBlocks encodes n groups of 12 input bytes into 16 base64 chars each, via
// the VSX/AltiVec vector facility (Lemire/Muła vectorised base64). Generated by
// go-asmgen (encode_ppc64x_gen.go), in encode_ppc64x.s. It emits ISA-3.0 (POWER9)
// instructions (LXVB16X/STXVB16X) that SIGILL on POWER8, so callers must gate it
// behind hasVSX (cpu.PPC64.IsPOWER9). encodeBlocksURL is the identical kernel with
// the -_ ASCII offset-LUT (only two entries of the VPERM offset table differ).
func encodeBlocks(dst, src []byte, n int)
func encodeBlocksURL(dst, src []byte, n int)

// encodeSIMD runs the encode kernel over the part of src where a 16-byte LXVB16X
// load stays in bounds (it reads 16 bytes per 12-byte group), reporting bytes
// consumed in src and written in dst so the caller can finish the tail with the
// stdlib. url selects the -_ (URL/RawURL) alphabet kernel over the +/ one. On a
// pre-POWER9 CPU it reports no progress so the whole input goes to the stdlib.
func encodeSIMD(dst, src []byte, url bool) (srcDone, dstDone int) {
	n := len(src)
	if !hasVSX || n < 16 {
		return 0, 0
	}
	groups := (n-16)/12 + 1
	if url {
		encodeBlocksURL(dst, src, groups)
	} else {
		encodeBlocks(dst, src, groups)
	}
	return groups * 12, groups * 16
}
