//go:build amd64

package base64

import "golang.org/x/sys/cpu"

// encodeSIMDMin / decodeSIMDMin are the smallest inputs an amd64 kernel touches
// (SSE encode needs 16 src bytes, SSE decode 16+8 chars). Below them Encode/Decode
// hand straight to the stdlib so a tiny input is never slower than encoding/base64.
const (
	encodeSIMDMin = 16
	decodeSIMDMin = 16 + 8
)

// encodeBlocksSSE (12 bytes -> 16 chars) and encodeBlocksAVX2 (24 -> 32) are the
// vectorised base64 encoders for the StdEncoding alphabet (+/); the URL-suffixed
// pair is the identical kernel with a -_ ASCII offset-LUT (the only difference is
// two entries of the PSHUFB offset table). Generated by go-asmgen (encode_gen.go),
// in encode_amd64.s.
func encodeBlocksSSE(dst, src []byte, n int)
func encodeBlocksAVX2(dst, src []byte, n int)
func encodeBlocksSSEURL(dst, src []byte, n int)
func encodeBlocksAVX2URL(dst, src []byte, n int)

var hasAVX2 = cpu.X86.HasAVX2

// encodeSIMD runs the widest available kernel over the part of src where its
// over-reading load stays in bounds, reporting bytes consumed/written so the
// caller finishes the tail. AVX2 reads 32 bytes per 24-byte group; SSE reads 16
// per 12. url selects the -_ (URL/RawURL) alphabet kernel over the +/ one.
func encodeSIMD(dst, src []byte, url bool) (srcDone, dstDone int) {
	n := len(src)
	if hasAVX2 && n >= 32 {
		groups := (n-32)/24 + 1
		if url {
			encodeBlocksAVX2URL(dst, src, groups)
		} else {
			encodeBlocksAVX2(dst, src, groups)
		}
		return groups * 24, groups * 32
	}
	// n >= encodeSIMDMin (16) is guaranteed by the caller, so the SSE path always
	// runs at least one group when AVX2 is unavailable.
	groups := (n-16)/12 + 1
	if url {
		encodeBlocksSSEURL(dst, src, groups)
	} else {
		encodeBlocksSSE(dst, src, groups)
	}
	return groups * 12, groups * 16
}
