// Code generated by go-asmgen. DO NOT EDIT.

//go:build ppc64le

#include "textflag.h"

TEXT ·encodeBlocks(SB), NOSPLIT, $0-56
	MOVD dst_base+0(FP), R3
	MOVD src_base+24(FP), R4
	MOVD n+48(FP), R5
	MOVD $ppcShuf<>(SB), R6
	LXVB16X (R6)(R0), VS39
	MOVD $ppcM0<>(SB), R6
	LXVB16X (R6)(R0), VS40
	MOVD $ppcM1<>(SB), R6
	LXVB16X (R6)(R0), VS41
	MOVD $ppcM2<>(SB), R6
	LXVB16X (R6)(R0), VS42
	MOVD $ppcM3<>(SB), R6
	LXVB16X (R6)(R0), VS43
	MOVD $ppcLut<>(SB), R6
	LXVB16X (R6)(R0), VS44
	MOVD $ppcS2<>(SB), R6
	LXVB16X (R6)(R0), VS45
	MOVD $ppcS4<>(SB), R6
	LXVB16X (R6)(R0), VS46
	MOVD $ppcS6<>(SB), R6
	LXVB16X (R6)(R0), VS47
	MOVD $ppcS8<>(SB), R6
	LXVB16X (R6)(R0), VS48
	MOVD $ppcC51<>(SB), R6
	LXVB16X (R6)(R0), VS49
	MOVD $ppcC25<>(SB), R6
	LXVB16X (R6)(R0), VS50
	MOVD $ppcC1<>(SB), R6
	LXVB16X (R6)(R0), VS51
	CMP R5, $0
	BEQ done
loop:
	LXVB16X (R4)(R0), VS32
	VPERM V0, V0, V7, V0
	VSRW V0, V13, V1
	VAND V1, V8, V1
	VSRW V0, V14, V2
	VAND V2, V9, V2
	VOR V2, V1, V1
	VSRW V0, V15, V2
	VAND V2, V10, V2
	VOR V2, V1, V1
	VSRW V0, V16, V2
	VAND V2, V11, V2
	VOR V2, V1, V1
	VSUBUBS V1, V17, V2
	VCMPGTUB V1, V18, V3
	VAND V3, V19, V3
	VADDUBM V2, V3, V2
	VPERM V12, V12, V2, V2
	VADDUBM V1, V2, V2
	STXVB16X VS34, (R3)(R0)
	ADD $12, R4
	ADD $16, R3
	ADD $-1, R5
	CMP R5, $0
	BNE loop
done:
	RET

DATA ppcShuf<>+0(SB)/1, $0x00
DATA ppcShuf<>+1(SB)/1, $0x01
DATA ppcShuf<>+2(SB)/1, $0x02
DATA ppcShuf<>+3(SB)/1, $0x00
DATA ppcShuf<>+4(SB)/1, $0x03
DATA ppcShuf<>+5(SB)/1, $0x04
DATA ppcShuf<>+6(SB)/1, $0x05
DATA ppcShuf<>+7(SB)/1, $0x00
DATA ppcShuf<>+8(SB)/1, $0x06
DATA ppcShuf<>+9(SB)/1, $0x07
DATA ppcShuf<>+10(SB)/1, $0x08
DATA ppcShuf<>+11(SB)/1, $0x00
DATA ppcShuf<>+12(SB)/1, $0x09
DATA ppcShuf<>+13(SB)/1, $0x0a
DATA ppcShuf<>+14(SB)/1, $0x0b
DATA ppcShuf<>+15(SB)/1, $0x00
GLOBL ppcShuf<>(SB), RODATA|NOPTR, $16

DATA ppcM0<>+0(SB)/1, $0x3f
DATA ppcM0<>+1(SB)/1, $0x00
DATA ppcM0<>+2(SB)/1, $0x00
DATA ppcM0<>+3(SB)/1, $0x00
DATA ppcM0<>+4(SB)/1, $0x3f
DATA ppcM0<>+5(SB)/1, $0x00
DATA ppcM0<>+6(SB)/1, $0x00
DATA ppcM0<>+7(SB)/1, $0x00
DATA ppcM0<>+8(SB)/1, $0x3f
DATA ppcM0<>+9(SB)/1, $0x00
DATA ppcM0<>+10(SB)/1, $0x00
DATA ppcM0<>+11(SB)/1, $0x00
DATA ppcM0<>+12(SB)/1, $0x3f
DATA ppcM0<>+13(SB)/1, $0x00
DATA ppcM0<>+14(SB)/1, $0x00
DATA ppcM0<>+15(SB)/1, $0x00
GLOBL ppcM0<>(SB), RODATA|NOPTR, $16

DATA ppcM1<>+0(SB)/1, $0x00
DATA ppcM1<>+1(SB)/1, $0x3f
DATA ppcM1<>+2(SB)/1, $0x00
DATA ppcM1<>+3(SB)/1, $0x00
DATA ppcM1<>+4(SB)/1, $0x00
DATA ppcM1<>+5(SB)/1, $0x3f
DATA ppcM1<>+6(SB)/1, $0x00
DATA ppcM1<>+7(SB)/1, $0x00
DATA ppcM1<>+8(SB)/1, $0x00
DATA ppcM1<>+9(SB)/1, $0x3f
DATA ppcM1<>+10(SB)/1, $0x00
DATA ppcM1<>+11(SB)/1, $0x00
DATA ppcM1<>+12(SB)/1, $0x00
DATA ppcM1<>+13(SB)/1, $0x3f
DATA ppcM1<>+14(SB)/1, $0x00
DATA ppcM1<>+15(SB)/1, $0x00
GLOBL ppcM1<>(SB), RODATA|NOPTR, $16

DATA ppcM2<>+0(SB)/1, $0x00
DATA ppcM2<>+1(SB)/1, $0x00
DATA ppcM2<>+2(SB)/1, $0x3f
DATA ppcM2<>+3(SB)/1, $0x00
DATA ppcM2<>+4(SB)/1, $0x00
DATA ppcM2<>+5(SB)/1, $0x00
DATA ppcM2<>+6(SB)/1, $0x3f
DATA ppcM2<>+7(SB)/1, $0x00
DATA ppcM2<>+8(SB)/1, $0x00
DATA ppcM2<>+9(SB)/1, $0x00
DATA ppcM2<>+10(SB)/1, $0x3f
DATA ppcM2<>+11(SB)/1, $0x00
DATA ppcM2<>+12(SB)/1, $0x00
DATA ppcM2<>+13(SB)/1, $0x00
DATA ppcM2<>+14(SB)/1, $0x3f
DATA ppcM2<>+15(SB)/1, $0x00
GLOBL ppcM2<>(SB), RODATA|NOPTR, $16

DATA ppcM3<>+0(SB)/1, $0x00
DATA ppcM3<>+1(SB)/1, $0x00
DATA ppcM3<>+2(SB)/1, $0x00
DATA ppcM3<>+3(SB)/1, $0x3f
DATA ppcM3<>+4(SB)/1, $0x00
DATA ppcM3<>+5(SB)/1, $0x00
DATA ppcM3<>+6(SB)/1, $0x00
DATA ppcM3<>+7(SB)/1, $0x3f
DATA ppcM3<>+8(SB)/1, $0x00
DATA ppcM3<>+9(SB)/1, $0x00
DATA ppcM3<>+10(SB)/1, $0x00
DATA ppcM3<>+11(SB)/1, $0x3f
DATA ppcM3<>+12(SB)/1, $0x00
DATA ppcM3<>+13(SB)/1, $0x00
DATA ppcM3<>+14(SB)/1, $0x00
DATA ppcM3<>+15(SB)/1, $0x3f
GLOBL ppcM3<>(SB), RODATA|NOPTR, $16

DATA ppcS2<>+0(SB)/1, $0x00
DATA ppcS2<>+1(SB)/1, $0x00
DATA ppcS2<>+2(SB)/1, $0x00
DATA ppcS2<>+3(SB)/1, $0x02
DATA ppcS2<>+4(SB)/1, $0x00
DATA ppcS2<>+5(SB)/1, $0x00
DATA ppcS2<>+6(SB)/1, $0x00
DATA ppcS2<>+7(SB)/1, $0x02
DATA ppcS2<>+8(SB)/1, $0x00
DATA ppcS2<>+9(SB)/1, $0x00
DATA ppcS2<>+10(SB)/1, $0x00
DATA ppcS2<>+11(SB)/1, $0x02
DATA ppcS2<>+12(SB)/1, $0x00
DATA ppcS2<>+13(SB)/1, $0x00
DATA ppcS2<>+14(SB)/1, $0x00
DATA ppcS2<>+15(SB)/1, $0x02
GLOBL ppcS2<>(SB), RODATA|NOPTR, $16

DATA ppcS4<>+0(SB)/1, $0x00
DATA ppcS4<>+1(SB)/1, $0x00
DATA ppcS4<>+2(SB)/1, $0x00
DATA ppcS4<>+3(SB)/1, $0x04
DATA ppcS4<>+4(SB)/1, $0x00
DATA ppcS4<>+5(SB)/1, $0x00
DATA ppcS4<>+6(SB)/1, $0x00
DATA ppcS4<>+7(SB)/1, $0x04
DATA ppcS4<>+8(SB)/1, $0x00
DATA ppcS4<>+9(SB)/1, $0x00
DATA ppcS4<>+10(SB)/1, $0x00
DATA ppcS4<>+11(SB)/1, $0x04
DATA ppcS4<>+12(SB)/1, $0x00
DATA ppcS4<>+13(SB)/1, $0x00
DATA ppcS4<>+14(SB)/1, $0x00
DATA ppcS4<>+15(SB)/1, $0x04
GLOBL ppcS4<>(SB), RODATA|NOPTR, $16

DATA ppcS6<>+0(SB)/1, $0x00
DATA ppcS6<>+1(SB)/1, $0x00
DATA ppcS6<>+2(SB)/1, $0x00
DATA ppcS6<>+3(SB)/1, $0x06
DATA ppcS6<>+4(SB)/1, $0x00
DATA ppcS6<>+5(SB)/1, $0x00
DATA ppcS6<>+6(SB)/1, $0x00
DATA ppcS6<>+7(SB)/1, $0x06
DATA ppcS6<>+8(SB)/1, $0x00
DATA ppcS6<>+9(SB)/1, $0x00
DATA ppcS6<>+10(SB)/1, $0x00
DATA ppcS6<>+11(SB)/1, $0x06
DATA ppcS6<>+12(SB)/1, $0x00
DATA ppcS6<>+13(SB)/1, $0x00
DATA ppcS6<>+14(SB)/1, $0x00
DATA ppcS6<>+15(SB)/1, $0x06
GLOBL ppcS6<>(SB), RODATA|NOPTR, $16

DATA ppcS8<>+0(SB)/1, $0x00
DATA ppcS8<>+1(SB)/1, $0x00
DATA ppcS8<>+2(SB)/1, $0x00
DATA ppcS8<>+3(SB)/1, $0x08
DATA ppcS8<>+4(SB)/1, $0x00
DATA ppcS8<>+5(SB)/1, $0x00
DATA ppcS8<>+6(SB)/1, $0x00
DATA ppcS8<>+7(SB)/1, $0x08
DATA ppcS8<>+8(SB)/1, $0x00
DATA ppcS8<>+9(SB)/1, $0x00
DATA ppcS8<>+10(SB)/1, $0x00
DATA ppcS8<>+11(SB)/1, $0x08
DATA ppcS8<>+12(SB)/1, $0x00
DATA ppcS8<>+13(SB)/1, $0x00
DATA ppcS8<>+14(SB)/1, $0x00
DATA ppcS8<>+15(SB)/1, $0x08
GLOBL ppcS8<>(SB), RODATA|NOPTR, $16

DATA ppcC51<>+0(SB)/1, $0x33
DATA ppcC51<>+1(SB)/1, $0x33
DATA ppcC51<>+2(SB)/1, $0x33
DATA ppcC51<>+3(SB)/1, $0x33
DATA ppcC51<>+4(SB)/1, $0x33
DATA ppcC51<>+5(SB)/1, $0x33
DATA ppcC51<>+6(SB)/1, $0x33
DATA ppcC51<>+7(SB)/1, $0x33
DATA ppcC51<>+8(SB)/1, $0x33
DATA ppcC51<>+9(SB)/1, $0x33
DATA ppcC51<>+10(SB)/1, $0x33
DATA ppcC51<>+11(SB)/1, $0x33
DATA ppcC51<>+12(SB)/1, $0x33
DATA ppcC51<>+13(SB)/1, $0x33
DATA ppcC51<>+14(SB)/1, $0x33
DATA ppcC51<>+15(SB)/1, $0x33
GLOBL ppcC51<>(SB), RODATA|NOPTR, $16

DATA ppcC25<>+0(SB)/1, $0x19
DATA ppcC25<>+1(SB)/1, $0x19
DATA ppcC25<>+2(SB)/1, $0x19
DATA ppcC25<>+3(SB)/1, $0x19
DATA ppcC25<>+4(SB)/1, $0x19
DATA ppcC25<>+5(SB)/1, $0x19
DATA ppcC25<>+6(SB)/1, $0x19
DATA ppcC25<>+7(SB)/1, $0x19
DATA ppcC25<>+8(SB)/1, $0x19
DATA ppcC25<>+9(SB)/1, $0x19
DATA ppcC25<>+10(SB)/1, $0x19
DATA ppcC25<>+11(SB)/1, $0x19
DATA ppcC25<>+12(SB)/1, $0x19
DATA ppcC25<>+13(SB)/1, $0x19
DATA ppcC25<>+14(SB)/1, $0x19
DATA ppcC25<>+15(SB)/1, $0x19
GLOBL ppcC25<>(SB), RODATA|NOPTR, $16

DATA ppcC1<>+0(SB)/1, $0x01
DATA ppcC1<>+1(SB)/1, $0x01
DATA ppcC1<>+2(SB)/1, $0x01
DATA ppcC1<>+3(SB)/1, $0x01
DATA ppcC1<>+4(SB)/1, $0x01
DATA ppcC1<>+5(SB)/1, $0x01
DATA ppcC1<>+6(SB)/1, $0x01
DATA ppcC1<>+7(SB)/1, $0x01
DATA ppcC1<>+8(SB)/1, $0x01
DATA ppcC1<>+9(SB)/1, $0x01
DATA ppcC1<>+10(SB)/1, $0x01
DATA ppcC1<>+11(SB)/1, $0x01
DATA ppcC1<>+12(SB)/1, $0x01
DATA ppcC1<>+13(SB)/1, $0x01
DATA ppcC1<>+14(SB)/1, $0x01
DATA ppcC1<>+15(SB)/1, $0x01
GLOBL ppcC1<>(SB), RODATA|NOPTR, $16

DATA ppcLut<>+0(SB)/1, $0x41
DATA ppcLut<>+1(SB)/1, $0x47
DATA ppcLut<>+2(SB)/1, $0xfc
DATA ppcLut<>+3(SB)/1, $0xfc
DATA ppcLut<>+4(SB)/1, $0xfc
DATA ppcLut<>+5(SB)/1, $0xfc
DATA ppcLut<>+6(SB)/1, $0xfc
DATA ppcLut<>+7(SB)/1, $0xfc
DATA ppcLut<>+8(SB)/1, $0xfc
DATA ppcLut<>+9(SB)/1, $0xfc
DATA ppcLut<>+10(SB)/1, $0xfc
DATA ppcLut<>+11(SB)/1, $0xfc
DATA ppcLut<>+12(SB)/1, $0xed
DATA ppcLut<>+13(SB)/1, $0xf0
DATA ppcLut<>+14(SB)/1, $0x00
DATA ppcLut<>+15(SB)/1, $0x00
GLOBL ppcLut<>(SB), RODATA|NOPTR, $16

